# Generated by Django 6.0.3 on 2026-04-11 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.groups'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('INVITE', 'Group Invite'), ('ALERT', 'General Alert')], default='ALERT', max_length=10),
        ),
    ]
