# Generated by Django 6.0.3 on 2026-04-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='posts/docs'),
        ),
        migrations.AddField(
            model_name='post',
            name='gradient_class',
            field=models.CharField(blank=True, choices=[('none', 'Standard (No Gradient)'), ('grad-ocean', 'Ocean Blue'), ('grad-forest', 'Forest Green'), ('grad-magma', 'Magma Red'), ('grad-midnight', 'Midnight Purple')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos'),
        ),
    ]
