# Generated by Django 6.0.3 on 2026-04-10 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups_in',
            field=models.ManyToManyField(related_name='members', to='core.groups'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
