# Generated by Django 6.0.3 on 2026-04-02 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='course',
        ),
    ]
