# Generated by Django 6.0.3 on 2026-04-02 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_unit_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.course'),
            preserve_default=False,
        ),
    ]
