# Generated by Django 6.0.3 on 2026-04-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_unit_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
