# Generated by Django 6.0.3 on 2026-04-10 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_groups_member_groups_is_official_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
