# Generated by Django 6.0.3 on 2026-04-03 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_unit_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.year'),
        ),
    ]
