# Generated by Django 6.0.3 on 2026-04-24 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_commentlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups_in',
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
