# Generated by Django 6.0.3 on 2026-04-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_group_alter_post_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_pic',
            field=models.ImageField(blank=True, null=True, upload_to='group_profile_pic'),
        ),
    ]
