# Generated by Django 5.2.13 on 2026-04-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_sharedpost_shared_to_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.FileField(blank=True, help_text='Attach music/audio to post', null=True, upload_to='posts/audio'),
        ),
    ]
