# Generated by Django 5.2.13 on 2026-06-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gradient_class',
            field=models.CharField(blank=True, choices=[('none', 'Standard (No Gradient)'), ('grad-ocean', 'Ocean Blue'), ('grad-forest', 'Forest Green'), ('grad-magma', 'Magma Red'), ('grad-midnight', 'Midnight Purple'), ('grad-desert', 'Desert Storm'), ('grad-stealth', 'Night Ops (Stealth)')], default='grad-ocean', max_length=50),
        ),
    ]
