# Generated by Django 5.2.13 on 2026-06-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_gradient_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='thumbnail_400',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/thumbnails'),
        ),
        migrations.AddField(
            model_name='postimage',
            name='thumbnail_800',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/thumbnails'),
        ),
    ]
