# Generated by Django 5.2.13 on 2026-06-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_postimage_thumbnail_400_postimage_thumbnail_800'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='posts/videos/posters'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_preview',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/previews'),
        ),
    ]
