# Generated by Django 5.2.13 on 2026-07-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_comment_parent_and_reply_count'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='posts_comme_post_id_eb3027_idx',
            old_name='posts_comment_post_parent_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='posts_comme_parent__f6f2e4_idx',
            old_name='posts_comment_parent_created_idx',
        ),
    ]
