# Generated by Django 5.2.13 on 2026-07-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_rename_posts_comment_post_parent_idx_posts_comme_post_id_eb3027_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gradient_class',
            field=models.CharField(blank=True, choices=[('none', 'Standard (No Gradient)'), ('grad-ocean', 'Ocean Blue'), ('grad-forest', 'Forest Green'), ('grad-magma', 'Magma Red'), ('grad-midnight', 'Midnight Purple'), ('grad-desert', 'Desert Storm'), ('grad-stealth', 'Night Ops (Stealth)'), ('bg-cosmic-stars', 'Cosmic Stars'), ('bg-spring-flora', 'Spring Flora'), ('bg-playful-doodles', 'Playful Doodles'), ('bg-magic-sparkles', 'Magic Sparkles')], default='grad-ocean', max_length=50),
        ),
    ]
