# Generated by Django 5.2.13 on 2026-07-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_post_gradient_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='has_signature',
            field=models.BooleanField(default=False),
        ),
    ]
