# Generated by Django 5.2.13 on 2026-07-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_post_has_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='custom_gradient_color1',
            field=models.CharField(blank=True, help_text='Custom gradient color 1 (hex)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='custom_gradient_color2',
            field=models.CharField(blank=True, help_text='Custom gradient color 2 (hex)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='custom_gradient_text',
            field=models.CharField(blank=True, help_text='Custom text for gradient patterns', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='gradient_class',
            field=models.CharField(blank=True, choices=[('none', 'Standard (No Gradient)'), ('grad-ocean', 'Ocean Blue'), ('grad-forest', 'Forest Green'), ('grad-magma', 'Magma Red'), ('grad-midnight', 'Midnight Purple'), ('grad-desert', 'Desert Storm'), ('grad-stealth', 'Night Ops (Stealth)'), ('bg-cosmic-stars', 'Cosmic Stars'), ('bg-spring-flora', 'Spring Flora'), ('bg-playful-doodles', 'Playful Doodles'), ('bg-magic-sparkles', 'Magic Sparkles'), ('bg-username-pattern', 'Signature Pattern'), ('bg-geometric-dots', 'Geometric Dots'), ('bg-diagonal-lines', 'Diagonal Lines'), ('bg-hexagon-mesh', 'Hexagon Mesh'), ('bg-circuit-board', 'Circuit Board'), ('bg-matrix-rain', 'Matrix Rain')], default='grad-ocean', max_length=50),
        ),
    ]
