# Generated by Django 5.2.13 on 2026-07-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_post_custom_gradient_color1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='custom_gradient_text_color',
            field=models.CharField(blank=True, help_text='Custom text color (hex)', max_length=7, null=True),
        ),
    ]
