# Generated by Django 5.2.13 on 2026-07-31 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_remove_documentrating_review_and_more'),
        ('posts', '0021_post_custom_gradient_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_posts', to='documents.document'),
        ),
    ]
