# Generated by Django 5.2.13 on 2026-08-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_post_shared_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail for gradient/text posts', null=True, upload_to='posts/thumbnails'),
        ),
    ]
