# Generated by Django 5.2.13 on 2026-09-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hls_playlist',
            field=models.CharField(blank=True, help_text='Relative path or CDN URL to the HLS master playlist (master.m3u8)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of the video in seconds (populated by ffprobe)', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('transcoding', 'Transcoding'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Processing state of the uploaded video', max_length=20),
        ),
    ]
