# Generated by Django 5.2.13 on 2026-09-06 09:26

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_faculty_department_and_bridge'),
        ('documents', '0009_programmeunit_academic_year_academiclevel_and_more'),
        ('groups', '0016_group_search_vector_group_group_search_vector_idx_and_more'),
        ('posts', '0027_alter_post_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video_transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='post_search_vector_idx'),
        ),
    ]
