# Generated by Django 5.2.13 on 2026-09-07 15:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_post_search_vector_post_video_transcript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=models.FileField(blank=True, help_text='Attach music/audio to post', max_length=500, null=True, upload_to='posts/audio'),
        ),
        migrations.AlterField(
            model_name='post',
            name='docs',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='posts/docs'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail for gradient/text posts', max_length=500, null=True, upload_to='posts/thumbnails'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, max_length=500, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='posts/videos'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_poster',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='posts/videos/posters'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_preview',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='posts/videos/previews'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='posts/images'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='thumbnail_400',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='posts/images/thumbnails'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='thumbnail_800',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='posts/images/thumbnails'),
        ),
    ]
