# Generated by Django 5.2.13 on 2026-09-07 21:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_alter_post_audio_alter_post_docs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
