# Generated by Django 5.2.13 on 2026-09-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_alter_post_share_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_height',
            field=models.PositiveIntegerField(blank=True, help_text='Height of the video in pixels', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video_width',
            field=models.PositiveIntegerField(blank=True, help_text='Width of the video in pixels', null=True),
        ),
    ]
