# Generated by Django 5.2.13 on 2026-09-26 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0018_migrate_pending_memberships'),
        ('posts', '0033_post_video_height_post_video_width'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sharedpost',
            name='unique_user_share',
        ),
        migrations.RemoveConstraint(
            model_name='sharedpost',
            name='unique_group_share',
        ),
        migrations.AddField(
            model_name='sharedpost',
            name='share_type',
            field=models.CharField(choices=[('post', 'Post'), ('app_link', 'Mobile App Link'), ('link', 'Custom Link')], default='post', max_length=32),
        ),
        migrations.AddField(
            model_name='sharedpost',
            name='shared_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sharedpost',
            name='shared_link_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharedpost',
            name='shared_link_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sharedpost',
            name='original_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='posts.post'),
        ),
        migrations.AddConstraint(
            model_name='sharedpost',
            constraint=models.UniqueConstraint(condition=models.Q(('original_post__isnull', False), ('shared_to__isnull', False)), fields=('original_post', 'sharer', 'shared_to'), name='unique_user_share'),
        ),
        migrations.AddConstraint(
            model_name='sharedpost',
            constraint=models.UniqueConstraint(condition=models.Q(('original_post__isnull', False), ('shared_to_group__isnull', False)), fields=('original_post', 'sharer', 'shared_to_group'), name='unique_group_share'),
        ),
        migrations.AddConstraint(
            model_name='sharedpost',
            constraint=models.CheckConstraint(condition=models.Q(('original_post__isnull', False), ('shared_link__isnull', False), _connector='OR'), name='share_post_or_link'),
        ),
    ]
