# Generated by Django 5.2.13 on 2026-09-28 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0016_linkpreview_media_type_linkpreview_remote_image_url'),
        ('posts', '0034_remove_sharedpost_unique_user_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_preview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='messaging.linkpreview'),
        ),
    ]
