# Generated by Django 5.2.13 on 2026-10-05 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0039_post_allow_downloads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='attachment_image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='attachment_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='comment',
            name='attachment_type',
            field=models.CharField(choices=[('none', 'None'), ('image', 'Image'), ('gif', 'GIF'), ('sticker', 'Sticker')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='attachment_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='postimagecomment',
            name='attachment_image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='postimagecomment',
            name='attachment_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='postimagecomment',
            name='attachment_type',
            field=models.CharField(choices=[('none', 'None'), ('image', 'Image'), ('gif', 'GIF'), ('sticker', 'Sticker')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='postimagecomment',
            name='attachment_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='postimagecomment',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='UserSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stickers/%Y/%m/')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_stickers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
