# Generated by Django 6.0.3 on 2026-04-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups_in',
            field=models.ManyToManyField(related_name='members_reverse', to='groups.groups'),
        ),
    ]
