# Generated by Django 6.0.3 on 2026-04-25 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_groups_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups_in',
        ),
    ]
