# Generated by Django 5.2.13 on 2026-04-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/default_pic1.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
