# Generated by Django 5.2.13 on 2026-05-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collaboration_status',
            field=models.CharField(blank=True, choices=[('open_to_projects', 'Open to Projects'), ('open_to_study_groups', 'Open to Study Groups'), ('open_to_networking', 'Open to Networking'), ('not_looking', 'Not Looking')], default='', help_text='Current collaboration availability', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='headline',
            field=models.CharField(blank=True, help_text='Professional tagline or headline', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.TextField(blank=True, help_text='Comma-separated interests'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='Portfolio website URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.JSONField(blank=True, default=list, help_text='List of projects with title, description, and link'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text='List of skills'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL'),
        ),
    ]
