# Generated by Django 5.2.13 on 2026-05-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_collaboration_status_user_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_onboarding',
            field=models.BooleanField(default=False, help_text='Whether user has completed the onboarding tour'),
        ),
    ]
