# Generated by Django 5.2.13 on 2026-04-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_theme_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceaccount',
            name='last_used',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='global_role',
            field=models.CharField(choices=[('PRESIDENT', 'President'), ('DELEGATE', 'Delegate'), ('VERIFIED', 'Verified'), ('NORMAL', 'Normal')], db_index=True, default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='deviceaccount',
            index=models.Index(fields=['user', 'device_id'], name='users_devic_user_id_bdc6b8_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceaccount',
            index=models.Index(fields=['device_id', 'last_used'], name='users_devic_device__e4406b_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'followed'], name='users_follo_followe_1a4669_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['followed', 'follower'], name='users_follo_followe_64e87c_idx'),
        ),
    ]
