# Generated by Django 5.2.13 on 2026-04-30 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0011_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.year'),
        ),
    ]
