# Generated by Django 5.2.13 on 2026-06-28 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_on_pinch',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Pinch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pinch_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinches_sent', to=settings.AUTH_USER_MODEL)),
                ('pinched_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinches_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pinch_user', 'pinched_user'], name='users_pinch_pinch_u_4df9e9_idx'), models.Index(fields=['created_at'], name='users_pinch_created_fef8e9_idx'), models.Index(fields=['pinched_user', 'created_at'], name='users_pinch_pinched_1ddbc5_idx')],
                'unique_together': {('pinch_user', 'pinched_user', 'created_at')},
            },
        ),
    ]
