# Generated by Django 5.2.13 on 2026-06-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_notify_on_pinch_pinch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pinch',
            unique_together=set(),
        ),
    ]
