# Generated by Django 5.2.13 on 2026-07-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_pinch_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_on_comment_reply',
            field=models.BooleanField(default=True),
        ),
    ]
