# Generated by Django 5.2.13 on 2026-07-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_notify_on_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='font_size_preference',
            field=models.CharField(choices=[('tiny', 'Tiny'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili')], default='en', max_length=5),
        ),
    ]
