# Generated by Django 5.2.13 on 2026-07-22 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_font_size_preference_user_language_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post_privacy',
            field=models.CharField(choices=[('PUBLIC', 'Everyone'), ('AUTHENTICATED', 'PwaniNet Users'), ('FOLLOWERS', 'Followers Only'), ('PRIVATE', 'Only Me')], default='PUBLIC', help_text='Default visibility for new posts', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_privacy',
            field=models.CharField(choices=[('PUBLIC', 'Everyone'), ('AUTHENTICATED', 'PwaniNet Users'), ('FOLLOWERS', 'Followers Only'), ('PRIVATE', 'Only Me')], default='PUBLIC', help_text='Who can view profile information', max_length=20),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker', '-created_at'], name='users_block_blocker_912f78_idx'), models.Index(fields=['blocked'], name='users_block_blocked_f74d46_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.CreateModel(
            name='HiddenAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hidden_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by', to=settings.AUTH_USER_MODEL)),
                ('hider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_authors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hider', '-created_at'], name='users_hidde_hider_i_299c34_idx'), models.Index(fields=['hidden_author'], name='users_hidde_hidden__f8036b_idx')],
                'unique_together': {('hider', 'hidden_author')},
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('login_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_activity', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_current', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', '-last_activity'], name='users_users_user_id_f9f20a_idx'), models.Index(fields=['session_key'], name='users_users_session_70af4d_idx'), models.Index(fields=['-last_activity'], name='users_users_last_ac_b5b272_idx')],
            },
        ),
    ]
