# Generated by Django 5.2.13 on 2026-07-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_post_privacy_user_profile_privacy_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='device_type',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], default='desktop', max_length=20),
        ),
    ]
