# Generated by Django 5.2.13 on 2026-07-31 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_programmeunit_academic_year_academiclevel_and_more'),
        ('users', '0022_usersession_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_level',
            field=models.ForeignKey(blank=True, help_text='Current academic level (Year 1, Year 2, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='documents.academiclevel'),
        ),
        migrations.AddField(
            model_name='user',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='Current academic year', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='documents.academicyear'),
        ),
        migrations.AddField(
            model_name='user',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='Current academic programme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='documents.programme'),
        ),
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Current semester', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='documents.semester'),
        ),
    ]
