# Generated by Django 5.2.13 on 2026-08-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_academic_level_user_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='font_family_preference',
            field=models.CharField(choices=[('default', 'Default (System)'), ('ibm_plex_serif', 'IBM Plex Serif'), ('manrope', 'Manrope'), ('playfair_display', 'Playfair Display'), ('romanesco', 'Romanesco'), ('story_script', 'Story Script')], default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='font_style_preference',
            field=models.CharField(choices=[('normal', 'Normal'), ('italic', 'Italic')], default='normal', max_length=10),
        ),
    ]
