# Generated by Django 5.2.13 on 2026-08-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_font_family_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='font_family_preference',
            field=models.CharField(choices=[('default', 'Default (System)'), ('inter', 'Inter'), ('roboto', 'Roboto'), ('ibm_plex_serif', 'IBM Plex Serif'), ('manrope', 'Manrope'), ('playfair_display', 'Playfair Display'), ('romanesco', 'Romanesco'), ('story_script', 'Story Script'), ('poppins', 'Poppins'), ('lora', 'Lora'), ('merriweather', 'Merriweather')], default='default', max_length=30),
        ),
    ]
