# Generated by Django 5.2.13 on 2026-08-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_user_font_family_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='font_family_preference',
            field=models.CharField(choices=[('default', 'Default (System)'), ('inter', 'Inter'), ('roboto', 'Roboto'), ('ibm_plex_serif', 'IBM Plex Serif'), ('manrope', 'Manrope'), ('playfair_display', 'Playfair Display'), ('romanesco', 'Romanesco'), ('story_script', 'Story Script'), ('poppins', 'Poppins'), ('lora', 'Lora'), ('merriweather', 'Merriweather'), ('dancing_script', 'Dancing Script'), ('great_vibes', 'Great Vibes'), ('parisienne', 'Parisienne'), ('satisfy', 'Satisfy'), ('cookie', 'Cookie'), ('italianno', 'Italianno'), ('tangerine', 'Tangerine')], default='default', max_length=30),
        ),
    ]
