# Generated by Django 5.2.13 on 2026-08-13 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_user_font_family_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfilePhotoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('profile', 'Profile Photo'), ('cover', 'Cover Photo')], db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_photo_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile_user', 'photo_type', '-created_at'], name='users_userp_profile_4adfe0_idx'), models.Index(fields=['user', '-created_at'], name='users_userp_user_id_77b377_idx')],
                'unique_together': {('user', 'profile_user', 'photo_type')},
            },
        ),
    ]
