# Generated by Django 5.2.13 on 2026-08-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_userprofilephotolike'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='audio_preference',
            field=models.CharField(choices=[('muted', 'Muted'), ('unmuted', 'Unmuted')], default='muted', help_text='Default audio state for video playback', max_length=10),
        ),
    ]
