# Generated by Django 5.2.13 on 2026-09-06 09:26

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0003_add_faculty_department_and_bridge'),
        ('documents', '0009_programmeunit_academic_year_academiclevel_and_more'),
        ('users', '0029_user_audio_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='user_search_vector_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('username', name='gin_trgm_ops'), name='user_username_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('first_name', name='gin_trgm_ops'), django.contrib.postgres.indexes.OpClass('last_name', name='gin_trgm_ops'), name='user_names_trgm_idx'),
        ),
    ]
