# Generated by Django 5.2.13 on 2026-09-10 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_user_search_vector_user_user_search_vector_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTwoFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(db_index=True, default=False)),
                ('encrypted_secret', models.TextField(help_text='Authenticated encrypted TOTP secret')),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_timestep', models.BigIntegerField(blank=True, help_text='Last successfully consumed TOTP timestep for replay protection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Two-Factor Configuration',
                'verbose_name_plural': 'User Two-Factor Configurations',
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(help_text='Cryptographic hash of the recovery code', max_length=255)),
                ('is_consumed', models.BooleanField(db_index=True, default=False)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recovery Code',
                'verbose_name_plural': 'Recovery Codes',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'is_consumed'], name='users_recov_user_id_8dd09f_idx')],
            },
        ),
    ]
