# Generated by Django 5.2.13 on 2026-09-26 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_usertwofactor_recoverycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('invite_type', models.CharField(choices=[('app_download', 'Mobile App Download'), ('platform_invite', 'Invite to PwaniNet')], db_index=True, default='platform_invite', max_length=32)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('conversions_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Invite',
                'verbose_name_plural': 'Platform Invites',
                'indexes': [models.Index(fields=['token'], name='users_platf_token_f042d0_idx'), models.Index(fields=['inviter', 'invite_type'], name='users_platf_inviter_03da5c_idx')],
                'unique_together': {('inviter', 'invite_type')},
            },
        ),
    ]
