# Generated by Django 5.2.13 on 2026-09-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_platforminvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroShowcaseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('center_reel', models.ImageField(upload_to='hero_showcase/reels/')),
                ('pwani_gate', models.ImageField(upload_to='hero_showcase/campus/')),
                ('pwanimate', models.ImageField(upload_to='hero_showcase/ai/')),
                ('doc_repo', models.ImageField(upload_to='hero_showcase/docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Showcase Set',
                'verbose_name_plural': 'Hero Showcase Sets',
            },
        ),
    ]
