# Generated by Django 5.2.13 on 2026-10-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_profile_picture_static_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_theme_preference',
            field=models.CharField(choices=[('default', 'Default'), ('ocean-breeze', 'Ocean Breeze'), ('sand-gradient', 'Sand Gradient'), ('swahili-wave', 'Swahili Wave'), ('midnight-coast', 'Midnight Coast'), ('forest-glow', 'Forest Glow'), ('pwani-neon', 'Pwani Neon')], default='default', max_length=30),
        ),
    ]
