# Generated by Django 5.2.13 on 2026-10-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_user_chat_theme_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_theme_preference',
            field=models.CharField(choices=[('default', 'Ocean Wave (Default)'), ('ocean-wave', 'Ocean Wave'), ('ocean-breeze', 'Ocean Breeze'), ('classic', 'Classic'), ('sand-gradient', 'Sand Gradient'), ('swahili-wave', 'Swahili Wave'), ('midnight-coast', 'Midnight Coast'), ('forest-glow', 'Forest Glow'), ('pwani-neon', 'Pwani Neon')], default='default', max_length=30),
        ),
    ]
