# Generated by Django 5.2.13 on 2026-07-03 11:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Semantic version (e.g., 1.0.0)', max_length=50, unique=True)),
                ('build_number', models.PositiveIntegerField(help_text='Incremental build number for ordering', unique=True)),
                ('release_title', models.CharField(help_text='User-friendly title for this release', max_length=200)),
                ('release_summary', models.TextField(help_text='Brief summary of this release')),
                ('release_type', models.CharField(choices=[('MAJOR', 'Major'), ('MINOR', 'Minor'), ('PATCH', 'Patch'), ('HOTFIX', 'Hotfix')], default='MINOR', help_text='Type of release', max_length=20)),
                ('mandatory_update', models.BooleanField(default=False, help_text='If True, users must update to continue using the app')),
                ('published', models.BooleanField(default=False, help_text='If True, release is visible to users')),
                ('minimum_supported_version', models.CharField(blank=True, help_text='Minimum version required for this update', max_length=50, null=True)),
                ('release_channel', models.CharField(choices=[('STABLE', 'Stable'), ('BETA', 'Beta'), ('ALPHA', 'Alpha'), ('NIGHTLY', 'Nightly'), ('CANARY', 'Canary')], default='STABLE', help_text='Release channel for future staged rollouts', max_length=20)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this release was published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this release', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
                'ordering': ['-build_number', '-release_date'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FEATURE', 'Feature'), ('IMPROVEMENT', 'Improvement'), ('BUG_FIX', 'Bug Fix'), ('SECURITY', 'Security'), ('KNOWN_ISSUE', 'Known Issue'), ('DEPRECATION', 'Deprecation')], help_text='Category of this release item', max_length=20)),
                ('title', models.CharField(help_text='Title of this item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this item')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for displaying items within a release')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release', models.ForeignKey(help_text='The release this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='releases.release')),
            ],
            options={
                'verbose_name': 'Release Item',
                'verbose_name_plural': 'Release Items',
                'ordering': ['display_order', 'category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserReleaseView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, help_text='Session key for anonymous users (optional)', max_length=100, null=True)),
                ('release', models.ForeignKey(help_text='Release that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='releases.release')),
                ('user', models.ForeignKey(help_text='User who viewed this release', on_delete=django.db.models.deletion.CASCADE, related_name='viewed_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Release View',
                'verbose_name_plural': 'User Release Views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['version'], name='releases_re_version_f72dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['build_number'], name='releases_re_build_n_3b21a8_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['published'], name='releases_re_publish_4f28ee_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['release_channel'], name='releases_re_release_84f970_idx'),
        ),
        migrations.AddIndex(
            model_name='releaseitem',
            index=models.Index(fields=['release', 'category'], name='releases_re_release_a90e63_idx'),
        ),
        migrations.AddIndex(
            model_name='releaseitem',
            index=models.Index(fields=['display_order'], name='releases_re_display_bb78b3_idx'),
        ),
        migrations.AddIndex(
            model_name='userreleaseview',
            index=models.Index(fields=['user', 'viewed_at'], name='releases_us_user_id_f6072a_idx'),
        ),
        migrations.AddIndex(
            model_name='userreleaseview',
            index=models.Index(fields=['release'], name='releases_us_release_838914_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userreleaseview',
            unique_together={('user', 'release')},
        ),
    ]
