# Generated by Django 5.2.13 on 2026-07-07 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='environment_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of environment configuration at release time'),
        ),
        migrations.AddField(
            model_name='release',
            name='is_current_release',
            field=models.BooleanField(default=False, help_text='If True, this is the currently deployed release'),
        ),
        migrations.AddField(
            model_name='release',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When this release was published', null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='published_by',
            field=models.ForeignKey(blank=True, help_text='Admin who published this release', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_releases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='release',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('TESTING', 'Testing'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Current status of the release', max_length=20),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_channel',
            field=models.CharField(choices=[('DEVELOPMENT', 'Development'), ('ALPHA', 'Alpha'), ('BETA', 'Beta'), ('RELEASE_CANDIDATE', 'Release Candidate'), ('STABLE', 'Stable')], default='STABLE', help_text='Release channel for future staged rollouts', max_length=20),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['status'], name='releases_re_status_5b1730_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['is_current_release'], name='releases_re_is_curr_45cce0_idx'),
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current_release', True)), fields=('is_current_release',), name='unique_current_release'),
        ),
    ]
