# Generated by Django 5.2.13 on 2026-08-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_release_environment_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Screenshot or image for this release item', null=True, upload_to='release_images/'),
        ),
        migrations.AddField(
            model_name='releaseitem',
            name='image_caption',
            field=models.CharField(blank=True, help_text='Caption for the image', max_length=200),
        ),
    ]
