# Generated by Django 5.2.13 on 2026-08-13 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0003_releaseitem_image_releaseitem_image_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='releaseitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='releaseitem',
            name='image_caption',
        ),
        migrations.CreateModel(
            name='ReleaseItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Screenshot or image for this release item', upload_to='release_images/')),
                ('caption', models.CharField(blank=True, help_text='Caption for the image', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for displaying images within the release item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release_item', models.ForeignKey(help_text='The release item this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='releases.releaseitem')),
            ],
            options={
                'verbose_name': 'Release Item Image',
                'verbose_name_plural': 'Release Item Images',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
