#!/bin/bash
# Terminal 3: Secure Global Uplink
cloudflared tunnel run --token eyJhIjoiZmY3ZDU4NmNmYjhkNzc1MDgwMjIxYjk0OWRhMzkxMTQiLCJzIjoiTjRlcmFGRlI2R3E4bnFoMTU3cWk1cDNlR2hYVzljZGRUczViSFZZT0xuTT0iLCJ0IjoiOWI1ODdhYmMtM2QyMy00OGY0LTllNjQtOTMyNDEyZTFhNDk1In0=



