# Generated by Django 6.0.3 on 2026-04-26 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_report_description_alter_report_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repost_children', to='posts.post'),
        ),
    ]
