# Generated by Django 5.2.13 on 2026-04-30 20:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_add_e2e_encryption_and_conversation_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_type', models.CharField(choices=[('solid', 'Solid Color'), ('gradient', 'CSS Gradient'), ('image', 'Image Wallpaper')], default='solid', max_length=10)),
                ('light_color', models.CharField(blank=True, help_text='Hex color for light mode', max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color')])),
                ('dark_color', models.CharField(blank=True, help_text='Hex color for dark mode', max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color')])),
                ('light_gradient_start', models.CharField(blank=True, help_text='Start color for light mode gradient', max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color')])),
                ('light_gradient_end', models.CharField(blank=True, help_text='End color for light mode gradient', max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color')])),
                ('dark_gradient_start', models.CharField(blank=True, help_text='Start color for dark mode gradient', max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color')])),
                ('dark_gradient_end', models.CharField(blank=True, help_text='End color for dark mode gradient', max_length=7, null=True, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color')])),
                ('gradient_angle', models.IntegerField(default=45, help_text='Gradient angle in degrees')),
                ('light_image', models.ImageField(blank=True, help_text='Image for light mode', null=True, upload_to='chat_themes/light/%Y/%m/')),
                ('dark_image', models.ImageField(blank=True, help_text='Image for dark mode', null=True, upload_to='chat_themes/dark/%Y/%m/')),
                ('image_fit', models.CharField(choices=[('cover', 'Cover'), ('contain', 'Contain'), ('repeat', 'Repeat')], default='cover', help_text='How to fit the image', max_length=10)),
                ('overlay_opacity', models.FloatField(default=0.3, help_text='Overlay opacity (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('light_overlay_color', models.CharField(default='#ffffff', help_text='Overlay color for light mode', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color')])),
                ('dark_overlay_color', models.CharField(default='#000000', help_text='Overlay color for dark mode', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='messaging.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_themes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'conversation'], name='messaging_c_user_id_c64180_idx')],
                'unique_together': {('user', 'conversation')},
            },
        ),
    ]
