"""
Unit and integration tests for Pwanimate Structure-Aware Document Chunker (Phase 2D).
"""

from django.test import TestCase
from django.contrib.auth import get_user_model

from documents.models import Document, DocumentVersion, Category
from pwanimate.models import DocumentChunk
from pwanimate.ingestion.types import (
    ElementType,
    LocationMetadata,
    ExtractedElement,
    ExtractedDocument,
)
from pwanimate.ingestion.chunker import (
    ChunkData,
    ChunkingConfig,
    StructureAwareChunker,
    chunk_document,
    create_document_chunks_from_data,
    estimate_tokens,
)

User = get_user_model()


class StructureAwareChunkerTestCase(TestCase):
    def setUp(self):
        self.user = User.objects.create_user(
            username='lecturer2',
            email='lecturer2@example.com',
            password='Password123!'
        )
        self.category = Category.objects.create(
            code='lecture_notes',
            name='Lecture Notes',
            is_active=True
        )
        self.document = Document.objects.create(
            title="Operating Systems CSC221",
            slug="operating-systems-csc221",
            category=self.category,
            uploaded_by=self.user,
            status='ready'
        )
        self.version = DocumentVersion.objects.create(
            document=self.document,
            version_number=1,
            created_by=self.user,
            is_latest=True
        )

    def test_prose_chunking_sizing_overlap_and_determinism(self):
        # Generate 6 paragraphs of academic prose, each around 120 tokens (~480 characters)
        paragraphs = [
            f"Paragraph {i}: Virtual memory provides an idealized abstraction of the storage resources "
            f"that are actually available on a given machine. The address space seen by a process is divided "
            f"into uniform blocks known as pages. The operating system maintains page tables to translate virtual "
            f"addresses generated by the central processing unit into physical addresses in main memory. "
            f"When an address translation fails because the requested page is not in physical RAM, a page fault exception occurs."
            for i in range(1, 7)
        ]

        elements = [
            ExtractedElement(
                element_type=ElementType.PARAGRAPH,
                text=p,
                location=LocationMetadata(page_number=1, block_index=idx)
            )
            for idx, p in enumerate(paragraphs)
        ]

        doc = ExtractedDocument(
            source_filename="virtual_memory.txt",
            format="txt",
            elements=elements
        )

        config = ChunkingConfig(target_min_tokens=250, target_max_tokens=400, overlap_tokens=60)
        chunks1 = chunk_document(doc, config=config)
        chunks2 = chunk_document(doc, config=config)

        # 1. Determinism
        self.assertEqual(len(chunks1), len(chunks2))
        for c1, c2 in zip(chunks1, chunks2):
            self.assertEqual(c1.content_hash, c2.content_hash)
            self.assertEqual(c1.chunk_index, c2.chunk_index)
            self.assertEqual(c1.content, c2.content)

        # 2. Sizing & Multiple Chunks
        self.assertGreaterEqual(len(chunks1), 2)
        for c in chunks1:
            self.assertGreater(c.token_count, 0)
            self.assertLessEqual(c.token_count, 500)

        # 3. Overlap continuity: chunk 1 should share text with chunk 0
        overlap_found = False
        words_c0 = set(chunks1[0].content.split()[-15:])
        words_c1 = set(chunks1[1].content.split()[:30])
        common = words_c0.intersection(words_c1)
        if len(common) >= 5:
            overlap_found = True
        self.assertTrue(overlap_found, "Consecutive chunks must contain overlapping tokens")

    def test_headings_as_section_context_not_isolated_chunks(self):
        elements = [
            ExtractedElement(
                element_type=ElementType.HEADING,
                text="Chapter 4: File Systems",
                location=LocationMetadata(page_number=10)
            ),
            ExtractedElement(
                element_type=ElementType.PARAGRAPH,
                text="File systems provide a mechanism for on-line storage and access to file contents.",
                location=LocationMetadata(page_number=10)
            ),
            ExtractedElement(
                element_type=ElementType.PARAGRAPH,
                text="The directory structure organizes and provides information about all files in the system.",
                location=LocationMetadata(page_number=10)
            ),
        ]

        doc = ExtractedDocument(
            source_filename="filesystems.pdf",
            format="pdf",
            elements=elements
        )

        chunks = chunk_document(doc)
        # Should NOT emit an isolated 1-line heading chunk
        self.assertEqual(len(chunks), 1)
        self.assertEqual(chunks[0].chunk_type, "paragraph")
        self.assertEqual(chunks[0].section_heading, "Chapter 4: File Systems")
        self.assertIn("File systems provide a mechanism", chunks[0].content)

    def test_multipage_pdf_provenance(self):
        elements = [
            ExtractedElement(
                element_type=ElementType.PARAGRAPH,
                text="This paragraph begins on page 1 and introduces disk storage architecture.",
                location=LocationMetadata(page_number=1)
            ),
            ExtractedElement(
                element_type=ElementType.PARAGRAPH,
                text="This paragraph is located on page 2 and elaborates on seek time and rotational latency.",
                location=LocationMetadata(page_number=2)
            ),
        ]

        doc = ExtractedDocument(
            source_filename="disks.pdf",
            format="pdf",
            elements=elements
        )

        chunks = chunk_document(doc)
        self.assertEqual(len(chunks), 1)
        # Verify page span
        self.assertEqual(chunks[0].page_number, 1)
        self.assertEqual(chunks[0].page_end, 2)

    def test_pptx_slide_atomic_and_speaker_notes(self):
        elements = [
            # Slide 1
            ExtractedElement(
                element_type=ElementType.HEADING,
                text="Distributed Consensus",
                location=LocationMetadata(slide_number=1),
                metadata={"is_slide_title": True}
            ),
            ExtractedElement(
                element_type=ElementType.PARAGRAPH,
                text="Paxos and Raft solve consensus in asynchronous networks with crash failures.",
                location=LocationMetadata(slide_number=1)
            ),
            ExtractedElement(
                element_type=ElementType.NOTES,
                text="Emphasize that FLP theorem proves impossibility in purely asynchronous models.",
                location=LocationMetadata(slide_number=1),
                metadata={"is_speaker_notes": True}
            ),
            # Slide 2
            ExtractedElement(
                element_type=ElementType.HEADING,
                text="Two-Phase Commit (2PC)",
                location=LocationMetadata(slide_number=2),
                metadata={"is_slide_title": True}
            ),
            ExtractedElement(
                element_type=ElementType.PARAGRAPH,
                text="2PC is an atomic commitment protocol across multiple database partitions.",
                location=LocationMetadata(slide_number=2)
            ),
        ]

        doc = ExtractedDocument(
            source_filename="consensus.pptx",
            format="pptx",
            elements=elements
        )

        chunks = chunk_document(doc)
        # 1 slide = 1 chunk
        self.assertEqual(len(chunks), 2)

        # Slide 1 verification
        c1 = chunks[0]
        self.assertEqual(c1.chunk_type, "slide")
        self.assertEqual(c1.slide_number, 1)
        self.assertEqual(c1.section_heading, "Distributed Consensus")
        self.assertIn("Paxos and Raft", c1.content)
        self.assertIn("[Speaker Notes]:", c1.content)
        self.assertTrue(c1.metadata.get("has_speaker_notes"))
        self.assertIn("FLP theorem", c1.metadata.get("speaker_notes", ""))

        # Slide 2 verification
        c2 = chunks[1]
        self.assertEqual(c2.chunk_type, "slide")
        self.assertEqual(c2.slide_number, 2)
        self.assertEqual(c2.section_heading, "Two-Phase Commit (2PC)")
        self.assertFalse(c2.metadata.get("has_speaker_notes"))

    def test_docx_interleaved_sequence_preserved(self):
        elements = [
            ExtractedElement(
                element_type=ElementType.HEADING,
                text="Relational Algebra",
                location=LocationMetadata(block_index=0)
            ),
            ExtractedElement(
                element_type=ElementType.PARAGRAPH,
                text="Relational algebra consists of a collection of operators taking relations as input.",
                location=LocationMetadata(block_index=1)
            ),
            ExtractedElement(
                element_type=ElementType.TABLE,
                text="Operator | Symbol | Description\nSelect | sigma | Filters tuples\nProject | pi | Filters columns",
                location=LocationMetadata(block_index=2),
                metadata={"row_count": 3}
            ),
            ExtractedElement(
                element_type=ElementType.PARAGRAPH,
                text="Additional join operators include theta join and natural join.",
                location=LocationMetadata(block_index=3)
            ),
        ]

        doc = ExtractedDocument(
            source_filename="relational_algebra.docx",
            format="docx",
            elements=elements
        )

        chunks = chunk_document(doc)
        # Heading -> Paragraph, Table, Paragraph sequence
        self.assertEqual(len(chunks), 3)

        # Chunk 0: Paragraph under heading
        self.assertEqual(chunks[0].chunk_type, "paragraph")
        self.assertEqual(chunks[0].section_heading, "Relational Algebra")

        # Chunk 1: Table
        self.assertEqual(chunks[1].chunk_type, "table")
        self.assertIn("Operator | Symbol", chunks[1].content)
        self.assertEqual(chunks[1].metadata.get("row_count"), 3)

        # Chunk 2: Trailing Paragraph
        self.assertEqual(chunks[2].chunk_type, "paragraph")
        self.assertIn("Additional join operators", chunks[2].content)

    def test_large_table_row_boundary_splitting(self):
        # Create a table with 30 rows that exceeds the max token threshold
        header = "ID | Student Name | Course | Grade"
        rows = [f"{i} | Student_{i} | CSC_{100+i} | Pass" for i in range(1, 40)]
        table_text = header + "\n" + "\n".join(rows)

        element = ExtractedElement(
            element_type=ElementType.TABLE,
            text=table_text,
            location=LocationMetadata(page_number=3),
            metadata={"row_count": 40}
        )

        doc = ExtractedDocument(
            source_filename="grades.pdf",
            format="pdf",
            elements=[element]
        )

        config = ChunkingConfig(target_max_tokens=200, max_hard_tokens=250)
        chunks = chunk_document(doc, config=config)

        self.assertGreater(len(chunks), 1)
        for c in chunks:
            self.assertEqual(c.chunk_type, "table")
            self.assertEqual(c.page_number, 3)
            # Table header should be preserved across split pieces
            self.assertTrue(c.content.startswith("ID | Student Name"))
            self.assertTrue(c.metadata.get("is_split_table"))

    def test_large_paragraph_sentence_splitting(self):
        # Create a single huge paragraph of 15 sentences (~800 tokens)
        sentences = [
            f"Sentence {i} explains in substantial depth the mathematical proofs governing algorithmic efficiency."
            for i in range(1, 20)
        ]
        large_para = " ".join(sentences)

        element = ExtractedElement(
            element_type=ElementType.PARAGRAPH,
            text=large_para,
            location=LocationMetadata(page_number=7)
        )

        doc = ExtractedDocument(
            source_filename="proofs.txt",
            format="txt",
            elements=[element]
        )

        config = ChunkingConfig(target_max_tokens=200)
        chunks = chunk_document(doc, config=config)

        self.assertGreater(len(chunks), 1)
        for c in chunks:
            self.assertEqual(c.chunk_type, "paragraph")
            self.assertEqual(c.page_number, 7)
            self.assertTrue(c.metadata.get("is_split_paragraph"))

    def test_exam_question_atomic_chunking(self):
        elements = [
            ExtractedElement(
                element_type=ElementType.PARAGRAPH,
                text="Question 1:\n(a) Explain the difference between pre-emptive and non-preemptive scheduling.\n(b) Calculate the average waiting time for the given processes.",
                location=LocationMetadata(page_number=1)
            ),
            ExtractedElement(
                element_type=ElementType.PARAGRAPH,
                text="Question 2:\nDescribe the four necessary conditions for deadlock occurrence.",
                location=LocationMetadata(page_number=1)
            ),
        ]

        doc = ExtractedDocument(
            source_filename="exam_2025.pdf",
            format="pdf",
            elements=elements
        )

        chunks = chunk_document(doc)
        self.assertEqual(len(chunks), 2)
        self.assertTrue(chunks[0].metadata.get("is_question"))
        self.assertIn("Question 1:", chunks[0].content)
        self.assertTrue(chunks[1].metadata.get("is_question"))
        self.assertIn("Question 2:", chunks[1].content)

    def test_code_block_intact(self):
        code_snippet = (
            "def binary_search(arr, target):\n"
            "    low, high = 0, len(arr) - 1\n"
            "    while low <= high:\n"
            "        mid = (low + high) // 2\n"
            "        if arr[mid] == target:\n"
            "            return mid\n"
            "        elif arr[mid] < target:\n"
            "            low = mid + 1\n"
            "        else:\n"
            "            high = mid - 1\n"
            "    return -1"
        )
        element = ExtractedElement(
            element_type=ElementType.CODE,
            text=code_snippet,
            location=LocationMetadata(page_number=4),
            metadata={"source_extension": "py"}
        )

        doc = ExtractedDocument(
            source_filename="search.py",
            format="py",
            elements=[element]
        )

        chunks = chunk_document(doc)
        self.assertEqual(len(chunks), 1)
        self.assertEqual(chunks[0].chunk_type, "code")
        self.assertIn("def binary_search", chunks[0].content)
        self.assertEqual(chunks[0].metadata.get("language"), "py")

    def test_empty_document_returns_empty_list(self):
        doc = ExtractedDocument(source_filename="empty.txt", format="txt", elements=[])
        chunks = chunk_document(doc)
        self.assertEqual(chunks, [])

    def test_persistence_helper_creates_document_chunks(self):
        elements = [
            ExtractedElement(
                element_type=ElementType.PARAGRAPH,
                text="Computer network protocols operate across hierarchical layers.",
                location=LocationMetadata(page_number=1, section_heading="Network Models")
            )
        ]
        doc = ExtractedDocument(source_filename="networks.pdf", format="pdf", elements=elements)
        chunks_data = chunk_document(doc)

        created_chunks = create_document_chunks_from_data(
            document_version=self.version,
            chunks=chunks_data
        )

        self.assertEqual(len(created_chunks), 1)
        db_chunk = DocumentChunk.objects.get(id=created_chunks[0].id)
        self.assertEqual(db_chunk.document, self.document)
        self.assertEqual(db_chunk.document_version, self.version)
        self.assertEqual(db_chunk.chunk_index, 0)
        self.assertFalse(db_chunk.is_active)  # Inactive by default until Phase 2E
        self.assertIn("Computer network protocols", db_chunk.content)
        self.assertIsNotNone(db_chunk.content_hash)
