# Generated by Django 5.2.13 on 2026-07-29 07:35

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique department code (e.g., 'CS')", max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2,10}$', 'Code must be uppercase letters only')])),
                ('name', models.CharField(help_text='Full name of the department', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=250, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the department')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AcademicUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique unit code (e.g., 'CSC221')", max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}\\d{3}$', 'Code must be like CSC221')])),
                ('name', models.CharField(help_text='Full name of the academic unit', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=250, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the academic unit')),
                ('credit_hours', models.PositiveSmallIntegerField(default=3, help_text='Credit hours for this unit')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this unit is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Unit',
                'verbose_name_plural': 'Academic Units',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='documents_a_code_4060f1_idx'), models.Index(fields=['slug'], name='documents_a_slug_798fdb_idx'), models.Index(fields=['is_active'], name='documents_a_is_acti_b6db87_idx')],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique identifier for the academic year (e.g., '2024/2025')", max_length=20, unique=True)),
                ('name', models.CharField(help_text="Human-readable name (e.g., '2024/2025')", max_length=50)),
                ('start_date', models.DateField(help_text='Start date of the academic year')),
                ('end_date', models.DateField(help_text='End date of the academic year')),
                ('is_current', models.BooleanField(default=False, help_text='Whether this is the current academic year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['code'], name='documents_a_code_d809b0_idx'), models.Index(fields=['is_current'], name='documents_a_is_curr_eb3d38_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('past_paper', 'Past Paper'), ('lecture_notes', 'Lecture Notes'), ('cat', 'CAT'), ('assignment', 'Assignment'), ('slides', 'Slides'), ('research', 'Research'), ('book', 'Book'), ('project', 'Project'), ('laboratory', 'Laboratory'), ('tutorial', 'Tutorial'), ('exam', 'Exam'), ('syllabus', 'Syllabus'), ('other', 'Other')], help_text='Unique category code', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable category name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this category')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class for this category', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='documents_c_code_2d727e_idx'), models.Index(fields=['is_active'], name='documents_c_is_acti_ef5b71_idx')],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Collection name', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=250, unique=True)),
                ('description', models.TextField(blank=True, help_text='Collection description')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('unlisted', 'Unlisted')], default='private', help_text='Collection visibility', max_length=20)),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image for the collection', upload_to='collection_covers/')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this collection is featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who owns this collection', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False, help_text='Whether the recipient can edit the collection')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(help_text='The shared collection', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.collection')),
                ('shared_by', models.ForeignKey(help_text='User who shared the collection', on_delete=django.db.models.deletion.CASCADE, related_name='shared_by_collections', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(help_text='User the collection is shared with', on_delete=django.db.models.deletion.CASCADE, related_name='shared_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collection Share',
                'verbose_name_plural': 'Collection Shares',
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title', max_length=500)),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=550, unique=True)),
                ('description', models.TextField(blank=True, help_text='Document description')),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('fr', 'French'), ('other', 'Other')], default='en', help_text='Document language', max_length=10)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('restricted', 'Restricted')], default='public', help_text='Document visibility', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready'), ('archived', 'Archived')], default='draft', help_text='Document processing status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='When the document was published', null=True)),
                ('category', models.ForeignKey(help_text='Document category', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.category')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the document', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Notes about this document in the collection')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the collection')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(help_text='User who added this document to the collection', on_delete=django.db.models.deletion.CASCADE, related_name='added_collection_items', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(help_text='The collection this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.collection')),
                ('document', models.ForeignKey(help_text='The document in this collection', on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='documents.document')),
            ],
            options={
                'verbose_name': 'Collection Item',
                'verbose_name_plural': 'Collection Items',
                'ordering': ['collection', 'order', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Author name (if not a registered user)', max_length=200)),
                ('author_type', models.CharField(choices=[('original', 'Original Author'), ('uploader', 'Uploader'), ('contributor', 'Contributor'), ('editor', 'Editor')], default='uploader', help_text='Type of authorship', max_length=20)),
                ('contribution_notes', models.TextField(blank=True, help_text='Notes about the contribution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(help_text='The document this author contributed to', on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='documents.document')),
                ('user', models.ForeignKey(blank=True, help_text='User author (if registered)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Author',
                'verbose_name_plural': 'Document Authors',
                'ordering': ['author_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text="User's notes about this bookmark")),
                ('is_favorite', models.BooleanField(default=False, help_text='Whether this is marked as a favorite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(help_text='The bookmarked document', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='documents.document')),
                ('user', models.ForeignKey(help_text='User who bookmarked the document', on_delete=django.db.models.deletion.CASCADE, related_name='document_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Bookmark',
                'verbose_name_plural': 'Document Bookmarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(help_text='Original filename when uploaded', max_length=500)),
                ('storage_path', models.CharField(help_text='Storage path/identifier for the file', max_length=1000)),
                ('mime_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('extension', models.CharField(help_text='File extension (e.g., pdf, docx)', max_length=20)),
                ('size_bytes', models.BigIntegerField(help_text='File size in bytes')),
                ('checksum', models.CharField(help_text='SHA-256 checksum for duplicate detection', max_length=64, unique=True)),
                ('storage_provider', models.CharField(choices=[('local', 'Local Storage'), ('s3', 'Amazon S3'), ('r2', 'Cloudflare R2'), ('b2', 'Backblaze B2'), ('azure', 'Azure Blob Storage'), ('minio', 'MinIO')], default='local', help_text='Storage backend used', max_length=20)),
                ('thumbnail_path', models.CharField(blank=True, help_text='Path to generated thumbnail', max_length=1000)),
                ('preview_path', models.CharField(blank=True, help_text='Path to generated preview', max_length=1000)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', help_text='Processing status', max_length=20)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this file', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document File',
                'verbose_name_plural': 'Document Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Session key for anonymous downloads', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the downloader', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the document was downloaded')),
                ('document', models.ForeignKey(help_text='The document that was downloaded', on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='documents.document')),
                ('user', models.ForeignKey(help_text='User who downloaded the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_downloads', to=settings.AUTH_USER_MODEL)),
                ('document_file', models.ForeignKey(help_text='The specific file that was downloaded', on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='documents.documentfile')),
            ],
            options={
                'verbose_name': 'Document Download',
                'verbose_name_plural': 'Document Downloads',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, help_text='Optional review text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(help_text='The rated document', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='documents.document')),
                ('user', models.ForeignKey(help_text='User who rated the document', on_delete=django.db.models.deletion.CASCADE, related_name='document_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Rating',
                'verbose_name_plural': 'Document Ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('copyright', 'Copyright Violation'), ('spam', 'Spam'), ('duplicate', 'Duplicate'), ('incorrect', 'Incorrect Information'), ('malware', 'Malware/Virus'), ('other', 'Other')], help_text='Reason for the report', max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the report')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', help_text='Report status', max_length=20)),
                ('review_notes', models.TextField(blank=True, help_text="Moderator's review notes")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the report was reviewed', null=True)),
                ('document', models.ForeignKey(help_text='The reported document', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='documents.document')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Moderator who reviewed the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who reported the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Report',
                'verbose_name_plural': 'Document Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the requested document', max_length=500)),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=550, unique=True)),
                ('description', models.TextField(help_text='Detailed description of what is being requested')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='open', help_text='Request status', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', help_text='Request priority', max_length=10)),
                ('fulfilled_at', models.DateTimeField(blank=True, help_text='When the request was fulfilled', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this request expires', null=True)),
                ('academic_unit', models.ForeignKey(blank=True, help_text='The academic unit this request is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requests', to='documents.academicunit')),
                ('category', models.ForeignKey(blank=True, help_text='The category of the requested document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requests', to='documents.category')),
                ('fulfilled_by', models.ForeignKey(blank=True, help_text='User who fulfilled the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_document_requests', to=settings.AUTH_USER_MODEL)),
                ('fulfilled_document', models.ForeignKey(blank=True, help_text='The document that fulfilled this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to='documents.document')),
                ('requested_by', models.ForeignKey(help_text='User who made the request', on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Request',
                'verbose_name_plural': 'Document Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRequestVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_request', models.ForeignKey(help_text='The request being voted on', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='documents.documentrequest')),
                ('user', models.ForeignKey(help_text='User who voted', on_delete=django.db.models.deletion.CASCADE, related_name='request_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Request Vote',
                'verbose_name_plural': 'Document Request Votes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(help_text='PostgreSQL search vector for full-text search', null=True)),
                ('title', models.CharField(db_index=True, help_text='Document title', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Document description')),
                ('category_code', models.CharField(db_index=True, help_text='Category code for filtering', max_length=50)),
                ('category_name', models.CharField(help_text='Category name for display', max_length=100)),
                ('academic_unit_codes', models.JSONField(blank=True, default=list, help_text='List of academic unit codes')),
                ('academic_unit_names', models.JSONField(blank=True, default=list, help_text='List of academic unit names')),
                ('semester_code', models.CharField(blank=True, db_index=True, help_text='Semester code', max_length=50, null=True)),
                ('academic_year_code', models.CharField(blank=True, db_index=True, help_text='Academic year code', max_length=20, null=True)),
                ('tag_names', models.JSONField(blank=True, default=list, help_text='List of tag names')),
                ('tag_slugs', models.JSONField(blank=True, default=list, help_text='List of tag slugs')),
                ('author_names', models.JSONField(blank=True, default=list, help_text='List of author names')),
                ('author_usernames', models.JSONField(blank=True, default=list, help_text='List of author usernames')),
                ('file_types', models.JSONField(blank=True, default=list, help_text='List of file extensions')),
                ('file_count', models.PositiveIntegerField(default=0, help_text='Number of files in the document')),
                ('ocr_text', models.TextField(blank=True, help_text='Extracted text from OCR (future feature)')),
                ('view_count', models.PositiveIntegerField(db_index=True, default=0, help_text='Total view count')),
                ('download_count', models.PositiveIntegerField(db_index=True, default=0, help_text='Total download count')),
                ('bookmark_count', models.PositiveIntegerField(db_index=True, default=0, help_text='Total bookmark count')),
                ('share_count', models.PositiveIntegerField(db_index=True, default=0, help_text='Total share count')),
                ('rating_average', models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Average rating', max_digits=3, null=True)),
                ('rating_count', models.PositiveIntegerField(default=0, help_text='Number of ratings')),
                ('popularity_score', models.FloatField(db_index=True, default=0.0, help_text='Computed popularity score for ranking')),
                ('created_at', models.DateTimeField(db_index=True, help_text='When the document was created')),
                ('updated_at', models.DateTimeField(db_index=True, help_text='When the document was last updated')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='When the document was published', null=True)),
                ('indexed_at', models.DateTimeField(auto_now=True, help_text='When this index was last updated')),
                ('document', models.OneToOneField(help_text='The document being indexed', on_delete=django.db.models.deletion.CASCADE, related_name='search_index', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Search Index',
                'verbose_name_plural': 'Document Search Indices',
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('copy_link', 'Copy Link'), ('other', 'Other')], help_text='Platform where the document was shared', max_length=20)),
                ('shared_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the document was shared')),
                ('document', models.ForeignKey(help_text='The shared document', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document')),
                ('user', models.ForeignKey(help_text='User who shared the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Share',
                'verbose_name_plural': 'Document Shares',
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(help_text='Sequential version number', validators=[django.core.validators.MinValueValidator(1)])),
                ('change_notes', models.TextField(blank=True, help_text='Notes about changes in this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=False, help_text='Whether this is the latest version')),
                ('created_by', models.ForeignKey(help_text='User who created this version', on_delete=django.db.models.deletion.CASCADE, related_name='created_document_versions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='The document this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='documentfile',
            name='document_version',
            field=models.ForeignKey(help_text='The document version this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.documentversion'),
        ),
        migrations.CreateModel(
            name='DocumentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='Session key for anonymous views', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the viewer', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('referrer', models.URLField(blank=True, help_text='Referrer URL')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the document was viewed')),
                ('duration_seconds', models.PositiveIntegerField(help_text='Duration of view in seconds', null=True)),
                ('document', models.ForeignKey(help_text='The document that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='documents.document')),
                ('user', models.ForeignKey(help_text='User who viewed the document (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document View',
                'verbose_name_plural': 'Document Views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique faculty code (e.g., 'SCI')", max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2,10}$', 'Code must be uppercase letters only')])),
                ('name', models.CharField(help_text='Full name of the faculty', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=250, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the faculty')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='documents_f_code_6d2551_idx'), models.Index(fields=['slug'], name='documents_f_slug_e87ca5_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileChecksum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(help_text='File checksum value', max_length=128, unique=True)),
                ('algorithm', models.CharField(choices=[('sha256', 'SHA-256'), ('sha512', 'SHA-512'), ('md5', 'MD5')], default='sha256', help_text='Hash algorithm used', max_length=10)),
                ('file_count', models.PositiveIntegerField(default=1, help_text='Number of files with this checksum')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, help_text='When this checksum was first seen')),
                ('last_seen_at', models.DateTimeField(auto_now=True, help_text='When this checksum was last seen')),
            ],
            options={
                'verbose_name': 'File Checksum',
                'verbose_name_plural': 'File Checksums',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['checksum'], name='documents_f_checksu_ed5e76_idx'), models.Index(fields=['algorithm'], name='documents_f_algorit_94728f_idx'), models.Index(fields=['-last_seen_at'], name='documents_f_last_se_2b11b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Moderation priority', max_length=10)),
                ('assigned_at', models.DateTimeField(blank=True, help_text='When the document was assigned', null=True)),
                ('estimated_review_time', models.DateTimeField(blank=True, help_text='Estimated time for review completion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Moderator assigned to this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_moderations', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(help_text='The document awaiting moderation', on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='documents.document')),
                ('submitted_by', models.ForeignKey(help_text='User who submitted the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation Queue',
                'verbose_name_plural': 'Moderation Queue',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('verified', 'Verified'), ('flagged', 'Flagged'), ('duplicate', 'Duplicate'), ('archived', 'Archived'), ('removed', 'Removed')], help_text='Unique status code', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Human-readable status name', max_length=50)),
                ('description', models.TextField(help_text='Description of when this status applies')),
                ('is_public', models.BooleanField(default=True, help_text='Whether documents with this status are visible to public')),
                ('is_searchable', models.BooleanField(default=True, help_text='Whether documents with this status appear in search')),
                ('is_downloadable', models.BooleanField(default=True, help_text='Whether documents with this status can be downloaded')),
                ('requires_action', models.BooleanField(default=False, help_text='Whether this status requires moderator action')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moderation Status',
                'verbose_name_plural': 'Moderation Statuses',
                'ordering': ['order', 'code'],
                'indexes': [models.Index(fields=['code'], name='documents_m_code_784674_idx'), models.Index(fields=['is_public'], name='documents_m_is_publ_03a93c_idx'), models.Index(fields=['is_searchable'], name='documents_m_is_sear_c640d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderation_notes', models.TextField(blank=True, help_text='Notes about moderation decisions')),
                ('status_changed_at', models.DateTimeField(auto_now=True, help_text='When the status last changed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(help_text='The document being moderated', on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='documents.document')),
                ('moderated_by', models.ForeignKey(blank=True, help_text='Moderator who last changed the status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_documents', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(help_text='Current moderation status', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.moderationstatus')),
            ],
            options={
                'verbose_name': 'Document Moderation',
                'verbose_name_plural': 'Document Moderations',
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique programme code (e.g., 'BSC-CS')", max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{2,20}$', 'Code must be alphanumeric uppercase')])),
                ('name', models.CharField(help_text='Full name of the programme', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=250, unique=True)),
                ('degree_type', models.CharField(help_text="Type of degree (e.g., 'Bachelor', 'Master', 'PhD')", max_length=50)),
                ('duration_years', models.PositiveSmallIntegerField(help_text='Duration of the programme in years')),
                ('description', models.TextField(blank=True, help_text='Description of the programme')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this programme is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='The department this programme belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='documents.department')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique school code (e.g., 'COMP')", max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2,10}$', 'Code must be uppercase letters only')])),
                ('name', models.CharField(help_text='Full name of the school', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=250, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the school')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(help_text='The faculty this school belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='documents.faculty')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(help_text='The school this department belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='documents.school'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3')], help_text='Semester number (1, 2, or 3)')),
                ('start_date', models.DateField(help_text='Start date of the semester')),
                ('end_date', models.DateField(help_text='End date of the semester')),
                ('is_current', models.BooleanField(default=False, help_text='Whether this is the current semester')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(help_text='The academic year this semester belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='documents.academicyear')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['academic_year', 'number'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_core', models.BooleanField(default=True, help_text='Whether this is a core unit for the programme')),
                ('is_elective', models.BooleanField(default=False, help_text='Whether this is an elective unit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_units', to='documents.academicunit')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_units', to='documents.programme')),
                ('semester', models.ForeignKey(help_text='The semester this unit is offered in this programme', on_delete=django.db.models.deletion.CASCADE, related_name='programme_units', to='documents.semester')),
            ],
            options={
                'verbose_name': 'Programme Unit',
                'verbose_name_plural': 'Programme Units',
            },
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='The semester this request is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requests', to='documents.semester'),
        ),
        migrations.CreateModel(
            name='DocumentAcademicUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True, help_text='Whether this is the primary academic unit for the document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.academicunit')),
                ('academic_year', models.ForeignKey(help_text='The academic year this document is relevant to', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.academicyear')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_units', to='documents.document')),
                ('semester', models.ForeignKey(help_text='The semester this document is relevant to', on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.semester')),
            ],
            options={
                'verbose_name': 'Document Academic Unit',
                'verbose_name_plural': 'Document Academic Units',
            },
        ),
        migrations.CreateModel(
            name='StorageBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name for this storage backend', max_length=100, unique=True)),
                ('backend_type', models.CharField(choices=[('local', 'Local Storage'), ('s3', 'Amazon S3'), ('r2', 'Cloudflare R2'), ('b2', 'Backblaze B2'), ('azure', 'Azure Blob Storage'), ('minio', 'MinIO')], help_text='Type of storage backend', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this backend is currently active')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default backend for new uploads')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Backend-specific configuration (credentials, buckets, etc.)')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Priority for backend selection (lower = higher priority)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Storage Backend',
                'verbose_name_plural': 'Storage Backends',
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='documents_s_is_acti_44e92a_idx'), models.Index(fields=['is_default'], name='documents_s_is_defa_16a45b_idx'), models.Index(fields=['priority'], name='documents_s_priorit_cbf2b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='StorageMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', help_text='Migration status', max_length=20)),
                ('files_migrated', models.PositiveIntegerField(default=0, help_text='Number of files successfully migrated')),
                ('files_failed', models.PositiveIntegerField(default=0, help_text='Number of files that failed to migrate')),
                ('total_files', models.PositiveIntegerField(help_text='Total number of files to migrate')),
                ('started_at', models.DateTimeField(blank=True, help_text='When migration started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When migration completed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if migration failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who initiated the migration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_migrations', to=settings.AUTH_USER_MODEL)),
                ('source_backend', models.ForeignKey(help_text='Source storage backend', on_delete=django.db.models.deletion.PROTECT, related_name='migrations_from', to='documents.storagebackend')),
                ('target_backend', models.ForeignKey(help_text='Target storage backend', on_delete=django.db.models.deletion.PROTECT, related_name='migrations_to', to='documents.storagebackend')),
            ],
            options={
                'verbose_name': 'Storage Migration',
                'verbose_name_plural': 'Storage Migrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this tag')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of documents using this tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['-usage_count', 'name'],
                'indexes': [models.Index(fields=['slug'], name='documents_t_slug_132f7a_idx'), models.Index(fields=['usage_count'], name='documents_t_usage_c_c89bc4_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to='documents.document')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to='documents.tag')),
            ],
            options={
                'verbose_name': 'Document Tag',
                'verbose_name_plural': 'Document Tags',
            },
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['slug'], name='documents_c_slug_b67f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['owner'], name='documents_c_owner_i_7be1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['visibility'], name='documents_c_visibil_35dc8e_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['is_featured'], name='documents_c_is_feat_5caed3_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['-created_at'], name='documents_c_created_09afb8_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionshare',
            index=models.Index(fields=['collection'], name='documents_c_collect_51afb8_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionshare',
            index=models.Index(fields=['shared_with'], name='documents_c_shared__f64fe2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionshare',
            unique_together={('collection', 'shared_with')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['slug'], name='documents_d_slug_3df491_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['visibility'], name='documents_d_visibil_72e869_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category'], name='documents_d_categor_fec314_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by'], name='documents_d_uploade_6455fb_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-created_at'], name='documents_d_created_71dced_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-published_at'], name='documents_d_publish_34515d_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['collection', 'order'], name='documents_c_collect_9a8cda_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['document'], name='documents_c_documen_c11095_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionitem',
            unique_together={('collection', 'document')},
        ),
        migrations.AddIndex(
            model_name='documentauthor',
            index=models.Index(fields=['document'], name='documents_d_documen_a29440_idx'),
        ),
        migrations.AddIndex(
            model_name='documentauthor',
            index=models.Index(fields=['user'], name='documents_d_user_id_7b75f0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentauthor',
            index=models.Index(fields=['author_type'], name='documents_d_author__31109a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentbookmark',
            index=models.Index(fields=['user', '-created_at'], name='documents_d_user_id_23f9bf_idx'),
        ),
        migrations.AddIndex(
            model_name='documentbookmark',
            index=models.Index(fields=['document'], name='documents_d_documen_8ab193_idx'),
        ),
        migrations.AddIndex(
            model_name='documentbookmark',
            index=models.Index(fields=['is_favorite'], name='documents_d_is_favo_d040e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentbookmark',
            unique_together={('document', 'user')},
        ),
        migrations.AddIndex(
            model_name='documentdownload',
            index=models.Index(fields=['document', '-downloaded_at'], name='documents_d_documen_c711b0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdownload',
            index=models.Index(fields=['user', '-downloaded_at'], name='documents_d_user_id_41bea9_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdownload',
            index=models.Index(fields=['document_file', '-downloaded_at'], name='documents_d_documen_f0d442_idx'),
        ),
        migrations.AddIndex(
            model_name='documentdownload',
            index=models.Index(fields=['-downloaded_at'], name='documents_d_downloa_c6e4f4_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrating',
            index=models.Index(fields=['document'], name='documents_d_documen_efdf07_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrating',
            index=models.Index(fields=['user'], name='documents_d_user_id_4242da_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrating',
            index=models.Index(fields=['rating'], name='documents_d_rating_8ffed5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentrating',
            unique_together={('document', 'user')},
        ),
        migrations.AddIndex(
            model_name='documentreport',
            index=models.Index(fields=['document', '-created_at'], name='documents_d_documen_0628f6_idx'),
        ),
        migrations.AddIndex(
            model_name='documentreport',
            index=models.Index(fields=['user', '-created_at'], name='documents_d_user_id_daa51a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentreport',
            index=models.Index(fields=['status'], name='documents_d_status_fd2c74_idx'),
        ),
        migrations.AddIndex(
            model_name='documentreport',
            index=models.Index(fields=['-created_at'], name='documents_d_created_bbe7b1_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequestvote',
            index=models.Index(fields=['document_request'], name='documents_d_documen_08daf0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequestvote',
            index=models.Index(fields=['user'], name='documents_d_user_id_5e95e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentrequestvote',
            unique_together={('document_request', 'user')},
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='documents_d_search__7c188b_gin'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=models.Index(fields=['title'], name='documents_d_title_0b4e43_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=models.Index(fields=['category_code'], name='documents_d_categor_7d824a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=models.Index(fields=['semester_code'], name='documents_d_semeste_8d8c38_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=models.Index(fields=['academic_year_code'], name='documents_d_academi_57e309_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=models.Index(fields=['view_count'], name='documents_d_view_co_d980c0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=models.Index(fields=['download_count'], name='documents_d_downloa_91b4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=models.Index(fields=['bookmark_count'], name='documents_d_bookmar_535fc2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=models.Index(fields=['popularity_score'], name='documents_d_popular_026297_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=models.Index(fields=['-created_at'], name='documents_d_created_732578_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=models.Index(fields=['-updated_at'], name='documents_d_updated_627af5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=models.Index(fields=['-published_at'], name='documents_d_publish_15812b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['document', '-shared_at'], name='documents_d_documen_5ed7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['user', '-shared_at'], name='documents_d_user_id_7ae332_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['platform', '-shared_at'], name='documents_d_platfor_16c165_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['-shared_at'], name='documents_d_shared__9d7b83_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'version_number'], name='documents_d_documen_68fe34_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['is_latest'], name='documents_d_is_late_fdd770_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['-created_at'], name='documents_d_created_b4fff4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['document_version'], name='documents_d_documen_debde6_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['checksum'], name='documents_d_checksu_9c4f18_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['processing_status'], name='documents_d_process_9f6b1f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['storage_provider'], name='documents_d_storage_969127_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfile',
            index=models.Index(fields=['-uploaded_at'], name='documents_d_uploade_360632_idx'),
        ),
        migrations.AddIndex(
            model_name='documentview',
            index=models.Index(fields=['document', '-viewed_at'], name='documents_d_documen_9fa40d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentview',
            index=models.Index(fields=['user', '-viewed_at'], name='documents_d_user_id_499096_idx'),
        ),
        migrations.AddIndex(
            model_name='documentview',
            index=models.Index(fields=['session_key', '-viewed_at'], name='documents_d_session_1de190_idx'),
        ),
        migrations.AddIndex(
            model_name='documentview',
            index=models.Index(fields=['-viewed_at'], name='documents_d_viewed__34ddee_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationqueue',
            index=models.Index(fields=['priority', 'created_at'], name='documents_m_priorit_a948b8_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationqueue',
            index=models.Index(fields=['assigned_to'], name='documents_m_assigne_913a85_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationqueue',
            index=models.Index(fields=['assigned_at'], name='documents_m_assigne_be3ac2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmoderation',
            index=models.Index(fields=['status'], name='documents_d_status__47e4a0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentmoderation',
            index=models.Index(fields=['status_changed_at'], name='documents_d_status__51bc59_idx'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['code'], name='documents_p_code_e48646_idx'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['slug'], name='documents_p_slug_cb0463_idx'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['department'], name='documents_p_departm_e02d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['is_active'], name='documents_p_is_acti_561282_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['code'], name='documents_s_code_129663_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['slug'], name='documents_s_slug_8b1995_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['faculty'], name='documents_s_faculty_ed50e6_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='documents_d_code_449e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['slug'], name='documents_d_slug_ce68b5_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['school'], name='documents_d_school__0cbebf_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['academic_year', 'number'], name='documents_s_academi_02b8da_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['is_current'], name='documents_s_is_curr_5a2892_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('number', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='programmeunit',
            index=models.Index(fields=['programme'], name='documents_p_program_69dc57_idx'),
        ),
        migrations.AddIndex(
            model_name='programmeunit',
            index=models.Index(fields=['academic_unit'], name='documents_p_academi_61c1cd_idx'),
        ),
        migrations.AddIndex(
            model_name='programmeunit',
            index=models.Index(fields=['semester'], name='documents_p_semeste_1b4d78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programmeunit',
            unique_together={('programme', 'academic_unit', 'semester')},
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['slug'], name='documents_d_slug_9feda7_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['status'], name='documents_d_status_a634ea_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['priority'], name='documents_d_priorit_445249_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['requested_by'], name='documents_d_request_6fe521_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['academic_unit'], name='documents_d_academi_da89a3_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['category'], name='documents_d_categor_3fa319_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrequest',
            index=models.Index(fields=['-created_at'], name='documents_d_created_c013a2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentacademicunit',
            index=models.Index(fields=['document'], name='documents_d_documen_fa8a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentacademicunit',
            index=models.Index(fields=['academic_unit'], name='documents_d_academi_499b0c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentacademicunit',
            index=models.Index(fields=['semester'], name='documents_d_semeste_c61ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='documentacademicunit',
            index=models.Index(fields=['academic_year'], name='documents_d_academi_0dc987_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentacademicunit',
            unique_together={('document', 'academic_unit', 'semester', 'academic_year')},
        ),
        migrations.AddIndex(
            model_name='storagemigration',
            index=models.Index(fields=['status'], name='documents_s_status_02fb5f_idx'),
        ),
        migrations.AddIndex(
            model_name='storagemigration',
            index=models.Index(fields=['-created_at'], name='documents_s_created_c305a6_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttag',
            index=models.Index(fields=['document'], name='documents_d_documen_5ff059_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttag',
            index=models.Index(fields=['tag'], name='documents_d_tag_id_8e4637_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documenttag',
            unique_together={('document', 'tag')},
        ),
    ]
