# Generated by Django 5.2.13 on 2026-07-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='file',
            field=models.FileField(default=0, help_text='The actual file', upload_to='documents/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
