# Generated by Django 5.2.13 on 2026-07-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='checksum',
            field=models.CharField(blank=True, help_text='SHA-256 checksum for duplicate detection', max_length=64, null=True),
        ),
    ]
