# Generated by Django 5.2.13 on 2026-07-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentfile_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfile',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of pages in the document', null=True),
        ),
    ]
