# Generated by Django 5.2.13 on 2026-07-30 22:43

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentfile_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsearchindex',
            name='academic_units_vector',
            field=django.contrib.postgres.search.SearchVectorField(help_text='Weighted search vector for academic units (high priority)', null=True),
        ),
        migrations.AddField(
            model_name='documentsearchindex',
            name='authors_vector',
            field=django.contrib.postgres.search.SearchVectorField(help_text='Weighted search vector for authors (medium priority)', null=True),
        ),
        migrations.AddField(
            model_name='documentsearchindex',
            name='category_vector',
            field=django.contrib.postgres.search.SearchVectorField(help_text='Weighted search vector for category (medium priority)', null=True),
        ),
        migrations.AddField(
            model_name='documentsearchindex',
            name='description_vector',
            field=django.contrib.postgres.search.SearchVectorField(help_text='Weighted search vector for description (medium priority)', null=True),
        ),
        migrations.AddField(
            model_name='documentsearchindex',
            name='filename_vector',
            field=django.contrib.postgres.search.SearchVectorField(help_text='Weighted search vector for filename (lowest priority)', null=True),
        ),
        migrations.AddField(
            model_name='documentsearchindex',
            name='ocr_text_vector',
            field=django.contrib.postgres.search.SearchVectorField(help_text='Weighted search vector for OCR text (lower priority)', null=True),
        ),
        migrations.AddField(
            model_name='documentsearchindex',
            name='primary_filename',
            field=models.CharField(blank=True, help_text='Primary filename for search', max_length=500),
        ),
        migrations.AddField(
            model_name='documentsearchindex',
            name='searchable_text',
            field=models.TextField(blank=True, help_text='Combined text for trigram similarity search'),
        ),
        migrations.AddField(
            model_name='documentsearchindex',
            name='tags_vector',
            field=django.contrib.postgres.search.SearchVectorField(help_text='Weighted search vector for tags (high priority)', null=True),
        ),
        migrations.AddField(
            model_name='documentsearchindex',
            name='title_vector',
            field=django.contrib.postgres.search.SearchVectorField(help_text='Weighted search vector for title (highest priority)', null=True),
        ),
        migrations.AddField(
            model_name='documentsearchindex',
            name='trending_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='Computed trending score for recent activity'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_vector'], name='documents_d_title_v_6a26eb_gin'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags_vector'], name='documents_d_tags_ve_f289af_gin'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['academic_units_vector'], name='documents_d_academi_3f2ecc_gin'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['category_vector'], name='documents_d_categor_ee5d2f_gin'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description_vector'], name='documents_d_descrip_63f906_gin'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['authors_vector'], name='documents_d_authors_1c4cc0_gin'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['ocr_text_vector'], name='documents_d_ocr_tex_4cf4c9_gin'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['filename_vector'], name='documents_d_filenam_41657b_gin'),
        ),
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=models.Index(fields=['trending_score'], name='documents_d_trendin_8ae851_idx'),
        ),
    ]
