# Generated by Django 5.2.13 on 2026-07-30 22:47

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_enable_pg_trgm_extension'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentsearchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['searchable_text'], name='doc_search_text_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
