# Generated by Django 5.2.13 on 2026-07-31 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_add_trigram_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrating',
            name='review',
        ),
        migrations.AlterField(
            model_name='documentrating',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, 'Thumbs Up'), (-1, 'Thumbs Down')], help_text='Rating: 1 for thumbs up, -1 for thumbs down'),
        ),
        migrations.CreateModel(
            name='DocumentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Total number of views')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Total number of downloads')),
                ('bookmark_count', models.PositiveIntegerField(default=0, help_text='Total number of bookmarks')),
                ('share_count', models.PositiveIntegerField(default=0, help_text='Total number of shares')),
                ('rating_count', models.PositiveIntegerField(default=0, help_text='Total number of ratings')),
                ('positive_rating_count', models.PositiveIntegerField(default=0, help_text='Number of thumbs up ratings')),
                ('negative_rating_count', models.PositiveIntegerField(default=0, help_text='Number of thumbs down ratings')),
                ('positive_rating_percentage', models.PositiveIntegerField(default=0, help_text='Percentage of positive ratings (0-100)')),
                ('negative_rating_percentage', models.PositiveIntegerField(default=0, help_text='Percentage of negative ratings (0-100)')),
                ('trending_score', models.DecimalField(decimal_places=2, default=0, help_text='Trending score for ranking', max_digits=10)),
                ('popularity_score', models.DecimalField(decimal_places=2, default=0, help_text='Popularity score for ranking', max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When analytics were last recalculated')),
                ('last_activity', models.DateTimeField(blank=True, help_text='Timestamp of the most recent engagement', null=True)),
                ('document', models.OneToOneField(help_text='The document this analytics belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='documents.document')),
            ],
            options={
                'verbose_name': 'Document Analytics',
                'verbose_name_plural': 'Document Analytics',
                'indexes': [models.Index(fields=['-trending_score'], name='documents_d_trendin_8e2103_idx'), models.Index(fields=['-popularity_score'], name='documents_d_popular_b7c555_idx'), models.Index(fields=['-last_updated'], name='documents_d_last_up_e49554_idx')],
            },
        ),
    ]
