# Generated by Django 5.2.13 on 2026-07-31 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_remove_documentrating_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeunit',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='The academic year this unit is offered', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programme_units', to='documents.academicyear'),
        ),
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5'), (6, 'Year 6'), (7, 'Masters'), (8, 'PhD')], help_text='Academic level number (1-8)', unique=True)),
                ('name', models.CharField(help_text='Human-readable level name', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this academic level')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this level is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Level',
                'verbose_name_plural': 'Academic Levels',
                'ordering': ['level'],
                'indexes': [models.Index(fields=['level'], name='documents_a_level_8c6a70_idx'), models.Index(fields=['is_active'], name='documents_a_is_acti_06397b_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='documentacademicunit',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='programmeunit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documentacademicunit',
            name='academic_level',
            field=models.ForeignKey(blank=True, help_text='The academic level this document is relevant to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.academiclevel'),
        ),
        migrations.AddField(
            model_name='programmeunit',
            name='academic_level',
            field=models.ForeignKey(blank=True, help_text='The academic level this unit is offered at', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programme_units', to='documents.academiclevel'),
        ),
        migrations.AlterUniqueTogether(
            name='documentacademicunit',
            unique_together={('document', 'academic_unit', 'academic_level', 'semester', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='programmeunit',
            unique_together={('programme', 'academic_unit', 'academic_level', 'academic_year', 'semester')},
        ),
        migrations.AddIndex(
            model_name='documentacademicunit',
            index=models.Index(fields=['academic_level'], name='documents_d_academi_65298e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentacademicunit',
            index=models.Index(fields=['academic_unit', 'academic_level', 'academic_year', 'semester'], name='documents_d_academi_65c111_idx'),
        ),
        migrations.AddIndex(
            model_name='programmeunit',
            index=models.Index(fields=['academic_level'], name='documents_p_academi_7694cf_idx'),
        ),
        migrations.AddIndex(
            model_name='programmeunit',
            index=models.Index(fields=['academic_year'], name='documents_p_academi_67f03a_idx'),
        ),
        migrations.AddIndex(
            model_name='programmeunit',
            index=models.Index(fields=['programme', 'academic_level', 'academic_year', 'semester'], name='documents_p_program_8e39f3_idx'),
        ),
    ]
