# Generated by Django 5.2.13 on 2026-09-07 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_programmeunit_academic_year_academiclevel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this document is available for viewing/downloading'),
        ),
        migrations.AlterField(
            model_name='documentshare',
            name='platform',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('copy_link', 'Copy Link'), ('profile', 'Profile'), ('group', 'Group'), ('other', 'Other')], help_text='Platform where the document was shared', max_length=20),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_available'], name='documents_d_is_avai_f95bfd_idx'),
        ),
    ]
