# Generated by Django 5.2.13 on 2026-09-07 21:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_document_is_available_alter_documentshare_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='share_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
