# Generated by Django 5.2.13 on 2026-09-07 21:34

import uuid
from django.db import migrations

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('documents', 'Document')
    for row in MyModel.objects.all():
        row.share_id = uuid.uuid4()
        row.save(update_fields=['share_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_document_share_id'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
