# Generated by Django 5.2.13 on 2026-09-07 21:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_populate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='share_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
