# Generated by Django 5.2.13 on 2026-09-30 05:00

import documents.documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_document_share_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='generated_format',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='generated_from_message_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_ai_generated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='documentfile',
            name='storage_private',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(choices=[('past_paper', 'Past Paper'), ('lecture_notes', 'Lecture Notes'), ('cat', 'CAT'), ('assignment', 'Assignment'), ('slides', 'Slides'), ('research', 'Research'), ('book', 'Book'), ('project', 'Project'), ('laboratory', 'Laboratory'), ('tutorial', 'Tutorial'), ('exam', 'Exam'), ('syllabus', 'Syllabus'), ('ai_generated', 'AI Generated Resource'), ('other', 'Other')], help_text='Unique category code', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='documentfile',
            name='file',
            field=models.FileField(help_text='The actual file', upload_to=documents.documents.models.document_file_upload_path),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('is_ai_generated', True)), fields=('uploaded_by', 'generated_from_message_id', 'generated_format'), name='unique_generated_resource_per_message_format'),
        ),
    ]
