# Generated by Django 5.2.13 on 2026-10-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_document_generated_format_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacademicunit',
            name='semester',
            field=models.ForeignKey(
                blank=True,
                help_text='The semester this document is relevant to',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='documents',
                to='documents.semester',
            ),
        ),
        migrations.AlterField(
            model_name='documentacademicunit',
            name='academic_year',
            field=models.ForeignKey(
                blank=True,
                help_text='The academic year this document is relevant to',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='documents',
                to='documents.academicyear',
            ),
        ),
        migrations.CreateModel(
            name='StudentUnitEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('auto_programme', 'Auto-Synced from Programme & Year'), ('custom_elective', 'Student Added (Elective)'), ('retake', 'Student Added (Retake / Carry-over)')], db_index=True, default='auto_programme', help_text='How this unit enrollment was created', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this unit is currently active for the student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_level', models.ForeignKey(blank=True, help_text='Academic level (Year) associated with this enrollment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_unit_enrollments', to='documents.academiclevel')),
                ('academic_unit', models.ForeignKey(help_text='The academic unit the student is enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='documents.academicunit')),
                ('academic_year', models.ForeignKey(blank=True, help_text='Academic year associated with this enrollment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_unit_enrollments', to='documents.academicyear')),
                ('semester', models.ForeignKey(blank=True, help_text='Semester associated with this enrollment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_unit_enrollments', to='documents.semester')),
                ('user', models.ForeignKey(help_text='The student enrolled in this academic unit', on_delete=django.db.models.deletion.CASCADE, related_name='unit_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Unit Enrollment',
                'verbose_name_plural': 'Student Unit Enrollments',
                'ordering': ['academic_unit__code'],
                'unique_together': {('user', 'academic_unit')},
            },
        ),
        migrations.AddIndex(
            model_name='studentunitenrollment',
            index=models.Index(fields=['user', 'is_active'], name='documents_s_user_id_active_idx'),
        ),
        migrations.AddIndex(
            model_name='studentunitenrollment',
            index=models.Index(fields=['academic_unit', 'is_active'], name='documents_s_unit_id_active_idx'),
        ),
        migrations.AddIndex(
            model_name='studentunitenrollment',
            index=models.Index(fields=['user', 'source'], name='documents_s_user_id_source_idx'),
        ),
    ]
