# Generated by Django 5.2.13 on 2026-07-29 09:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_school_course_school'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique department code (e.g., 'CS')", max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2,10}$', 'Code must be uppercase letters only')])),
                ('name', models.CharField(help_text='Full name of the department', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=250, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the department')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique faculty code (e.g., 'SCI')", max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2,10}$', 'Code must be uppercase letters only')])),
                ('name', models.CharField(help_text='Full name of the faculty', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly slug', max_length=250, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the faculty')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, help_text="Unique course code (e.g., 'BSC-CS')", max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{2,20}$', 'Code must be alphanumeric uppercase')]),
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='degree_type',
            field=models.CharField(blank=True, help_text="Type of degree (e.g., 'Bachelor', 'Master', 'PhD', 'Diploma')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the course'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_years',
            field=models.PositiveSmallIntegerField(blank=True, default=4, help_text='Duration of the course in years', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this course is currently active'),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly slug', max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Full name of the course/program', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Legacy field - use department instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.school'),
        ),
        migrations.AlterField(
            model_name='year',
            name='level',
            field=models.PositiveIntegerField(help_text='Year of study (1, 2, 3, 4, etc.)'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The department this course belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.department'),
        ),
        migrations.AddField(
            model_name='school',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Link to new Department model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_schools', to='courses.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(help_text='The faculty this department belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='courses.faculty'),
        ),
        migrations.CreateModel(
            name='CourseAcademicUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_core', models.BooleanField(default=True, help_text='Whether this is a core unit for the course')),
                ('is_elective', models.BooleanField(default=False, help_text='Whether this is an elective unit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_unit', models.ForeignKey(help_text='Reference to the academic unit in documents domain', on_delete=django.db.models.deletion.CASCADE, related_name='course_units', to='documents.academicunit')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_academic_units', to='courses.course')),
                ('semester', models.ForeignKey(help_text='The semester this unit is offered in this course', on_delete=django.db.models.deletion.CASCADE, related_name='course_units', to='documents.semester')),
                ('year_level', models.ForeignKey(help_text='The year level this unit is offered in this course', on_delete=django.db.models.deletion.CASCADE, related_name='course_academic_units', to='courses.year')),
            ],
            options={
                'ordering': ['course', 'year_level', 'semester'],
                'indexes': [models.Index(fields=['course'], name='courses_cou_course__f8e73b_idx'), models.Index(fields=['academic_unit'], name='courses_cou_academi_04753a_idx'), models.Index(fields=['year_level'], name='courses_cou_year_le_5e2232_idx'), models.Index(fields=['semester'], name='courses_cou_semeste_26cf96_idx')],
                'unique_together': {('course', 'academic_unit', 'year_level', 'semester')},
            },
        ),
    ]
