# Generated by Django 5.2.13 on 2026-09-13 06:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_faculty_department_and_bridge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['code'], 'verbose_name': 'School', 'verbose_name_plural': 'Schools'},
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this department is currently active'),
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(blank=True, help_text='The school this department belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='courses.school'),
        ),
        migrations.AddField(
            model_name='school',
            name='code',
            field=models.CharField(choices=[('SEDU', 'School of Education'), ('SHSS', 'School of Humanities and Social Sciences'), ('SPAS', 'School of Pure and Applied Sciences'), ('SAAB', 'School of Agricultural Sciences and Agribusiness'), ('SEES', 'School of Environmental and Earth Sciences'), ('SHHS', 'School of Health and Human Sciences'), ('SBE', 'School of Business and Economics')], default='SPAS', help_text='Official Pwani University school code', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this school is currently active'),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The department this course belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.department'),
        ),
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Parent School', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.school'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text="Unique department code (e.g., 'COMP', 'EDCI')", max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]{2,10}$', 'Code must be 2-10 uppercase alphanumeric or hyphen characters.')]),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Legacy faculty this department belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='courses.faculty'),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly slug', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Legacy link to Department model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_schools', to='courses.department'),
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of the school'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(help_text='Full name of the school', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly slug', max_length=220, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('school', 'name')},
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Official PU Programme Code (e.g., 'BSC-CS', 'BED-SCI')", max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]{3,30}$', 'Programme code must be uppercase alphanumeric with dashes.')])),
                ('name', models.CharField(help_text='Full programme title', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly slug', max_length=280, unique=True)),
                ('academic_level', models.CharField(choices=[('ARTISAN', 'TVET Artisan Certificate'), ('CRAFT_CERT', 'TVET Craft Certificate'), ('DIPLOMA', 'Diploma / TVET Diploma'), ('BACHELOR', 'Undergraduate Degree (Bachelor)'), ('POSTGRAD_DIPLOMA', 'Postgraduate Diploma'), ('MASTERS', 'Masters'), ('PHD', 'Doctor of Philosophy (PhD)')], default='BACHELOR', help_text='Statutory academic level', max_length=25)),
                ('duration_years', models.PositiveSmallIntegerField(default=4, help_text='Duration of the programme in years')),
                ('description', models.TextField(blank=True, help_text='Description of the programme')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this programme is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='Department hosting this programme', on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='courses.department')),
                ('school', models.ForeignKey(help_text='Parent School administering this programme', on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='courses.school')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='Link to statutory Programme model', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_courses', to='courses.programme'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['code'], name='courses_pro_code_218577_idx'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['school'], name='courses_pro_school__a4e199_idx'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['department'], name='courses_pro_departm_d7e3cc_idx'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['academic_level'], name='courses_pro_academi_ac21bf_idx'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['is_active'], name='courses_pro_is_acti_9c620b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programme',
            unique_together={('name', 'academic_level')},
        ),
    ]
