# Generated by Django 5.2.13 on 2026-04-30 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_conversationtheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationtheme',
            name='dark_image_hash',
            field=models.CharField(blank=True, help_text='Hash for image deduplication', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='conversationtheme',
            name='dark_image_size',
            field=models.PositiveIntegerField(blank=True, help_text='Optimized image size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='conversationtheme',
            name='light_image_hash',
            field=models.CharField(blank=True, help_text='Hash for image deduplication', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='conversationtheme',
            name='light_image_size',
            field=models.PositiveIntegerField(blank=True, help_text='Optimized image size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='conversationtheme',
            name='dark_image',
            field=models.ImageField(blank=True, help_text='Image for dark mode', null=True, upload_to='chat_themes/dark/%Y/%m/', validators=[django.core.validators.RegexValidator('.*\\.(jpg|jpeg|png|gif|webp)$', 'Only image files (JPG, PNG, GIF, WebP) are allowed')]),
        ),
        migrations.AlterField(
            model_name='conversationtheme',
            name='light_image',
            field=models.ImageField(blank=True, help_text='Image for light mode', null=True, upload_to='chat_themes/light/%Y/%m/', validators=[django.core.validators.RegexValidator('.*\\.(jpg|jpeg|png|gif|webp)$', 'Only image files (JPG, PNG, GIF, WebP) are allowed')]),
        ),
    ]
