# Generated by Django 5.2.13 on 2026-05-13 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_update_pending_message_state_machine'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pendingmessage',
            new_name='messaging_p_user_id_2bbaef_idx',
            old_name='messaging_p_user_id_6c5f5e_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingmessage',
            new_name='messaging_p_convers_05453f_idx',
            old_name='messaging_p_convers_8f3a2c_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingmessage',
            new_name='messaging_p_temp_id_ea4180_idx',
            old_name='messaging_p_temp_id_4e1b3a_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingmessage',
            new_name='messaging_p_server__2b01da_idx',
            old_name='messaging_p_server_5e2b1a_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingmessage',
            new_name='messaging_p_created_e7bef8_idx',
            old_name='messaging_p_created_5d2c1b_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingmessage',
            new_name='messaging_p_status_8f1033_idx',
            old_name='messaging_p_status_c_8f3c2b_idx',
        ),
    ]
