# Generated by Django 5.2.13 on 2026-05-17 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0013_rename_messaging_p_user_id_6c5f5e_idx_messaging_p_user_id_2bbaef_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='global_caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('media_group', 'Media Group'), ('system', 'System'), ('audio', 'Audio')], default='text', max_length=20),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message_attachments/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=20)),
                ('caption', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('size', models.BigIntegerField(default=0)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['message', 'order'], name='messaging_m_message_2fb2fd_idx'), models.Index(fields=['file_type'], name='messaging_m_file_ty_7bc063_idx')],
            },
        ),
    ]
