# Generated by Django 5.2.13 on 2026-05-18 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0014_message_global_caption_message_message_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=2048, unique=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, help_text='Cached OG image', null=True, upload_to='link_previews/%Y/%m/%d/')),
                ('favicon', models.ImageField(blank=True, help_text='Cached favicon', null=True, upload_to='link_favicons/%Y/%m/%d/')),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fetch_error', models.TextField(blank=True, null=True)),
                ('fetch_failed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Link Preview',
                'verbose_name_plural': 'Link Previews',
                'ordering': ['-cached_at'],
                'indexes': [models.Index(fields=['url'], name='messaging_l_url_cabede_idx'), models.Index(fields=['cached_at'], name='messaging_l_cached__adc44e_idx')],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='link_preview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.linkpreview'),
        ),
    ]
