# Generated by Django 5.2.13 on 2026-09-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0015_linkpreview_message_link_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkpreview',
            name='media_type',
            field=models.CharField(blank=True, default='link', max_length=50),
        ),
        migrations.AddField(
            model_name='linkpreview',
            name='remote_image_url',
            field=models.URLField(blank=True, help_text='Fallback remote image URL', max_length=2048, null=True),
        ),
    ]
