# Generated by Django 5.2.13 on 2026-09-15 14:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0013_alter_document_share_id'),
        ('pwanimate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField(help_text='Zero-based sequence index within the document version', validators=[django.core.validators.MinValueValidator(0)])),
                ('content', models.TextField(help_text='Extracted text content of the chunk')),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 hash of content for change and duplicate detection', max_length=64)),
                ('chunk_type', models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('table', 'Table'), ('slide', 'Slide'), ('notes', 'Notes'), ('code', 'Code'), ('text', 'Text')], db_index=True, default='paragraph', help_text='Semantic structural element type', max_length=30)),
                ('page_number', models.PositiveIntegerField(blank=True, db_index=True, help_text='Starting page number (1-indexed, for paginated formats like PDF)', null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, help_text='Ending page number if chunk spans multiple pages', null=True)),
                ('slide_number', models.PositiveIntegerField(blank=True, db_index=True, help_text='Slide number (1-indexed, for presentations like PPTX)', null=True)),
                ('section_heading', models.CharField(blank=True, default='', help_text='Active section or chapter heading context', max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional location provenance (bbox coordinates, table row count, notes flags)')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Whether this chunk is active and eligible for retrieval')),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Lifecycle status of vector embedding generation', max_length=20)),
                ('embedding_model', models.CharField(blank=True, default='', help_text='Model identifier used to produce vector embeddings', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(help_text='Source document', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
                ('document_version', models.ForeignKey(help_text='Specific document version that produced this chunk', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.documentversion')),
            ],
            options={
                'verbose_name': 'Document Chunk',
                'verbose_name_plural': 'Document Chunks',
                'ordering': ['document_version', 'chunk_index'],
                'indexes': [models.Index(fields=['document_version', 'chunk_index'], name='pwanimate_d_documen_473500_idx'), models.Index(fields=['document_version', 'is_active'], name='pwanimate_d_documen_9c97fb_idx'), models.Index(fields=['document', 'is_active'], name='pwanimate_d_documen_7a24eb_idx'), models.Index(fields=['page_number'], name='pwanimate_d_page_nu_37aa0e_idx'), models.Index(fields=['slide_number'], name='pwanimate_d_slide_n_f760a9_idx')],
                'constraints': [models.UniqueConstraint(fields=('document_version', 'chunk_index'), name='pwanimate_chunk_version_index_uniq'), models.CheckConstraint(condition=models.Q(('chunk_index__gte', 0)), name='pwanimate_chunk_index_non_negative'), models.CheckConstraint(condition=models.Q(('content', ''), _negated=True), name='pwanimate_chunk_content_not_empty')],
            },
        ),
    ]
