# Generated by Django 5.2.13 on 2026-09-15 16:34

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwanimate', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='Vector embedding of chunk content (768 dimensions for text-embedding-004)', null=True),
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='embedding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Lifecycle status of vector embedding generation', max_length=20),
        ),
    ]
