# Generated by Django 5.2.13 on 2026-09-18 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwanimate', '0004_pwanimateconversation_pwanimatemessage_and_more'),
        ('users', '0031_usertwofactor_recoverycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PwanimatePreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pwanimate_preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(blank=True, default='', help_text='Optional preferred name Pwanimate uses when addressing the student', max_length=50)),
                ('tone', models.CharField(choices=[('neutral', 'Neutral'), ('friendly', 'Friendly'), ('professional', 'Professional'), ('academic', 'Academic')], db_index=True, default='neutral', help_text='Assistant conversational tone', max_length=20)),
                ('response_style', models.CharField(choices=[('concise', 'Concise'), ('balanced', 'Balanced'), ('detailed', 'Detailed')], db_index=True, default='balanced', help_text='Assistant response formatting style', max_length=20)),
                ('personal_instructions', models.TextField(blank=True, default='', help_text='User-authored stylistic guidance for Pwanimate (maximum 500 characters)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pwanimate Preferences',
                'verbose_name_plural': 'Pwanimate Preferences',
            },
        ),
    ]
