# Generated by Django 5.2.13 on 2026-09-27 09:48

import django.core.validators
import django.db.models.deletion
import pwanimate.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwanimate', '0005_pwanimatepreferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PwanimateAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Secure, UUID-addressed file path', max_length=500, upload_to=pwanimate.models.pwanimate_attachment_upload_path)),
                ('file_name', models.CharField(help_text='Sanitized original display filename', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes', validators=[django.core.validators.MinValueValidator(1)])),
                ('mime_type', models.CharField(db_index=True, help_text='Validated MIME type', max_length=100)),
                ('attachment_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document')], db_index=True, default='document', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='pwanimate.pwanimateconversation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='pwanimate.pwanimatemessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pwanimate_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='pwanimate_p_user_id_9f2449_idx'), models.Index(fields=['conversation', 'created_at'], name='pwanimate_p_convers_54714c_idx'), models.Index(fields=['message'], name='pwanimate_p_message_bf98d6_idx')],
            },
        ),
    ]
