# Generated by Django 6.0.3 on 2026-04-25 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('INVITE', 'Group Invite'), ('ALERT', 'General Alert'), ('LIKE', 'Post Like'), ('FOLLOW', 'New Follower')], default='ALERT', max_length=10)),
                ('msg', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groups')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
