# Generated by Django 6.0.3 on 2026-04-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('INVITE', 'Group Invite'), ('ALERT', 'General Alert'), ('LIKE', 'Post Like'), ('FOLLOW', 'New Follower'), ('GROUP_REQUEST', 'Group Join Request'), ('GROUP_APPROVED', 'Group Join Approved')], default='ALERT', max_length=20),
        ),
    ]
