# Generated by Django 6.0.3 on 2026-04-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='group_covers/'),
        ),
    ]
