# Generated by Django 6.0.3 on 2026-04-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='join_policy',
            field=models.CharField(choices=[('open', 'Open'), ('approval', 'Requires Approval'), ('invite', 'Invite Only')], default='open', max_length=20),
        ),
    ]
