# Generated by Django 5.2.13 on 2026-05-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_membership_joined_at_alter_membership_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='auto_join_on_signup',
            field=models.BooleanField(default=False, help_text='Automatically enroll new users matching course/year into this group'),
        ),
    ]
