# Generated by Django 5.2.13 on 2026-08-15 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_announcement_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='attachment',
        ),
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='announcements/attachments')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='groups.announcement')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['announcement', '-uploaded_at'], name='groups_anno_announc_c8fb50_idx')],
            },
        ),
    ]
