# Generated by Django 5.2.13 on 2026-08-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_multiple_announcement_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementattachment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/thumbnails'),
        ),
    ]
