# Generated by Django 5.2.13 on 2026-08-15 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_programmeunit_academic_year_academiclevel_and_more'),
        ('groups', '0011_add_attachment_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementattachment',
            name='attachment_type',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document')], default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='announcementattachment',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_attachments', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='announcementattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='announcements/attachments'),
        ),
        migrations.AddIndex(
            model_name='announcementattachment',
            index=models.Index(fields=['attachment_type'], name='groups_anno_attachm_b376fc_idx'),
        ),
    ]
