# Generated by Django 5.2.13 on 2026-08-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_update_attachment_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='edit_permission',
            field=models.CharField(choices=[('admins_only', 'Admins Only'), ('admins_moderators', 'Admins and Moderators')], default='admins_only', help_text='Who can edit group details', max_length=30),
        ),
        migrations.AddField(
            model_name='group',
            name='post_visibility',
            field=models.CharField(choices=[('everyone', 'Everyone in Pwaninet'), ('members_only', 'Only Members')], default='members_only', help_text='Who can view group posts in the main feed', max_length=20),
        ),
    ]
