# Generated by Django 5.2.13 on 2026-08-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_group_edit_permission_group_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_permission',
            field=models.CharField(choices=[('admins_only', 'Admins Only'), ('all_members', 'All Members')], default='admins_only', help_text='Who can invite users to the group', max_length=30),
        ),
    ]
