# Generated by Django 5.2.13 on 2026-09-06 09:26

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_faculty_department_and_bridge'),
        ('groups', '0015_groupmessage_groupmessageattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='group',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='group_search_vector_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('name', name='gin_trgm_ops'), name='group_name_trgm_idx'),
        ),
    ]
