# Generated by Django 6.0.3 on 2026-04-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('group_pic', models.ImageField(blank=True, null=True, upload_to='group_profile_pic')),
                ('is_official', models.BooleanField(default=False)),
            ],
        ),
    ]
