# Generated by Django 6.0.3 on 2026-04-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notifications_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('INVITE', 'Group Invite'), ('ALERT', 'General Alert'), ('LIKE', 'Post Like'), ('FOLLOW', 'New Follower'), ('GROUP_REQUEST', 'Group Join Request'), ('GROUP_APPROVED', 'Group Join Approved'), ('GROUP_REJECTED', 'Group Join Rejected')], db_index=True, default='ALERT', max_length=20),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
