# Generated by Django 5.2.13 on 2026-06-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('INVITE', 'Group Invite'), ('ALERT', 'General Alert'), ('LIKE', 'Post Like'), ('FOLLOW', 'New Follower'), ('GROUP_REQUEST', 'Group Join Request'), ('GROUP_APPROVED', 'Group Join Approved'), ('GROUP_REJECTED', 'Group Join Rejected'), ('POST_SHARED', 'Post Shared to User'), ('POST_SHARED_TO_GROUP', 'Post Shared to Group'), ('PINCH', 'Profile Pinch')], db_index=True, default='ALERT', max_length=20),
        ),
    ]
