# Generated by Django 5.2.13 on 2026-08-03 12:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_alter_notifications_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventArchive',
            fields=[
                ('event_id', models.UUIDField(primary_key=True, serialize=False)),
                ('event_data', models.JSONField(help_text='Complete event data as JSON')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('original_timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'Event Archive',
                'verbose_name_plural': 'Event Archives',
                'ordering': ['-original_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PlatformEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique event identifier', primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text='Event type following canonical naming convention', max_length=100)),
                ('source', models.CharField(choices=[('SOCIAL_PLATFORM', 'Social Platform'), ('DOCUMENT_REPOSITORY', 'Document Repository'), ('WORKSPACE_PLATFORM', 'Workspace Platform'), ('COURSE_PLATFORM', 'Course Platform'), ('STUDY_PLATFORM', 'Study Platform'), ('COLLABORATION_PLATFORM', 'Collaboration Platform'), ('MEETING_PLATFORM', 'Meeting Platform'), ('CHAT_PLATFORM', 'Chat Platform'), ('AI_PLATFORM', 'AI Platform'), ('NOTIFICATION_ENGINE', 'Notification Engine'), ('AUTHENTICATION_SERVICE', 'Authentication Service'), ('ADMINISTRATIVE_CONSOLE', 'Administrative Console'), ('ACADEMIC_PLATFORM', 'Academic Platform'), ('STORAGE_SERVICE', 'Storage Service'), ('SYSTEM_SCHEDULER', 'System Scheduler')], db_index=True, help_text='The subsystem that published this event', max_length=50)),
                ('action', models.CharField(db_index=True, help_text='The action that occurred (past tense)', max_length=50)),
                ('target_type', models.CharField(db_index=True, help_text='Type of the target object (e.g., Post, Comment, Group)', max_length=50)),
                ('target_id', models.CharField(db_index=True, help_text='ID of the target object', max_length=100)),
                ('context_type', models.CharField(blank=True, db_index=True, help_text='Type of the context (e.g., Workspace, Course)', max_length=50, null=True)),
                ('context_id', models.CharField(blank=True, db_index=True, help_text='ID of the context', max_length=100, null=True)),
                ('audience', models.CharField(blank=True, choices=[('SPECIFIC_USER', 'Specific User'), ('WORKSPACE_MEMBERS', 'Workspace Members'), ('COURSE_MEMBERS', 'Course Members'), ('FOLLOWERS', 'Followers'), ('ADMINISTRATORS', 'Administrators'), ('EVERYONE', 'Everyone'), ('CUSTOM_GROUP', 'Custom Group')], help_text='Intended audience for this event', max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event-specific information')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the event occurred')),
                ('version', models.CharField(default='1.0', help_text='Event schema version', max_length=10)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, help_text='Groups related events into workflows', null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The user or system that caused this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Event',
                'verbose_name_plural': 'Platform Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type'], name='notificatio_event_t_26574d_idx'), models.Index(fields=['actor'], name='notificatio_actor_i_6c6f1e_idx'), models.Index(fields=['source'], name='notificatio_source_19b1d6_idx'), models.Index(fields=['target_type', 'target_id'], name='notificatio_target__b07538_idx'), models.Index(fields=['context_type', 'context_id'], name='notificatio_context_4e3fd4_idx'), models.Index(fields=['timestamp'], name='notificatio_timesta_3b639a_idx'), models.Index(fields=['correlation_id'], name='notificatio_correla_a78e99_idx')],
            },
        ),
    ]
