# Generated by Django 5.2.13 on 2026-08-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_create_platform_event_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformevent',
            name='source',
            field=models.CharField(choices=[('POSTS', 'Posts'), ('GROUPS', 'Groups'), ('USERS', 'Users'), ('DOCUMENTS', 'Documents'), ('COURSES', 'Courses'), ('MESSAGING', 'Messaging'), ('PROJECTS', 'Projects'), ('CORE', 'Core'), ('NOTIFICATIONS', 'Notifications'), ('AUTHENTICATION', 'Authentication'), ('ADMIN', 'Admin'), ('STORAGE', 'Storage'), ('SYSTEM', 'System')], db_index=True, help_text='The subsystem that published this event', max_length=50),
        ),
    ]
