# Generated by Django 5.2.13 on 2026-08-03 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_add_releases_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationObject',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Globally unique notification identifier', primary_key=True, serialize=False)),
                ('source_events', models.JSONField(default=list, help_text='List of Platform Event IDs that generated this notification')),
                ('notification_type', models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('MENTION', 'Mention'), ('ASSIGNMENT', 'Assignment'), ('MEETING', 'Meeting'), ('WORKSPACE', 'Workspace'), ('DOCUMENT', 'Document'), ('SECURITY', 'Security'), ('SYSTEM', 'System'), ('AI', 'AI'), ('GROUP', 'Group'), ('FOLLOW', 'Follow'), ('PINCH', 'Pinch'), ('INVITE', 'Invite'), ('SHARE', 'Share')], db_index=True, help_text='Semantic type of the notification', max_length=20)),
                ('category', models.CharField(choices=[('SOCIAL', 'Social'), ('ACADEMIC', 'Academic'), ('WORKSPACE', 'Workspace'), ('DOCUMENT', 'Document'), ('SECURITY', 'Security'), ('SYSTEM', 'System'), ('AI', 'AI')], db_index=True, help_text='Broader category for preference management', max_length=20)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('NORMAL', 'Normal'), ('LOW', 'Low')], db_index=True, default='NORMAL', help_text='Priority level for delivery and presentation', max_length=10)),
                ('title', models.CharField(help_text='Concise human-readable headline', max_length=255)),
                ('summary', models.TextField(blank=True, help_text='Additional context that may evolve during aggregation')),
                ('context_type', models.CharField(blank=True, db_index=True, help_text='Type of context (e.g., Course, Workspace)', max_length=50, null=True)),
                ('context_id', models.CharField(blank=True, db_index=True, help_text='ID of the context', max_length=100, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('QUEUED', 'Queued'), ('DELIVERED', 'Delivered'), ('SEEN', 'Seen'), ('READ', 'Read'), ('ARCHIVED', 'Archived'), ('EXPIRED', 'Expired')], db_index=True, default='CREATED', help_text='Current lifecycle status', max_length=20)),
                ('delivery_policy', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('SCHEDULED', 'Scheduled'), ('DELAYED', 'Delayed'), ('DIGEST', 'Digest')], default='IMMEDIATE', help_text='Intended delivery policy', max_length=20)),
                ('aggregation_key', models.CharField(blank=True, db_index=True, help_text='Key for grouping related notifications', max_length=255, null=True)),
                ('event_count', models.PositiveIntegerField(default=1, help_text='Number of merged events')),
                ('first_event_time', models.DateTimeField(blank=True, help_text='Timestamp of first event', null=True)),
                ('latest_event_time', models.DateTimeField(blank=True, help_text='Timestamp of latest event', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification-specific information')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the notification was first created (immutable)')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification time (aggregation updates this)')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='When this notification becomes irrelevant', null=True)),
                ('recipient', models.ForeignKey(help_text='The user who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notification_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Object',
                'verbose_name_plural': 'Notification Objects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ACCEPT', 'Accept'), ('DECLINE', 'Decline'), ('JOIN', 'Join'), ('SNOOZE', 'Snooze'), ('REVIEW', 'Review'), ('OPEN', 'Open'), ('VIEW', 'View'), ('DELETE', 'Delete'), ('ARCHIVE', 'Archive'), ('MARK_READ', 'Mark as Read'), ('CUSTOM', 'Custom')], help_text='Type of action', max_length=20)),
                ('label', models.CharField(help_text='Human-readable label for the action', max_length=50)),
                ('url', models.CharField(blank=True, help_text='URL to navigate when action is clicked', max_length=500)),
                ('method', models.CharField(default='GET', help_text='HTTP method for the action (GET, POST, etc.)', max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Additional payload data for the action')),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary action')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order for the action')),
                ('notification', models.ForeignKey(help_text='The notification this action belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='notifications.notificationobject')),
            ],
            options={
                'verbose_name': 'Notification Action',
                'verbose_name_plural': 'Notification Actions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='notificationobject',
            index=models.Index(fields=['recipient'], name='notificatio_recipie_7dd7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationobject',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_ebfe78_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationobject',
            index=models.Index(fields=['category'], name='notificatio_categor_96bda4_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationobject',
            index=models.Index(fields=['priority'], name='notificatio_priorit_5e5236_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationobject',
            index=models.Index(fields=['status'], name='notificatio_status_e9ac44_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationobject',
            index=models.Index(fields=['aggregation_key'], name='notificatio_aggrega_a24b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationobject',
            index=models.Index(fields=['created_at'], name='notificatio_created_3caece_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationobject',
            index=models.Index(fields=['expires_at'], name='notificatio_expires_c39589_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationobject',
            index=models.Index(fields=['context_type', 'context_id'], name='notificatio_context_4c18fa_idx'),
        ),
    ]
