# Generated by Django 5.2.13 on 2026-08-03 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_create_notification_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('GLOBAL', 'Global'), ('CATEGORY', 'Category'), ('TYPE', 'Type'), ('CONTEXT', 'Context')], db_index=True, help_text='Preference level (GLOBAL, CATEGORY, TYPE, CONTEXT)', max_length=20)),
                ('category', models.CharField(blank=True, db_index=True, help_text='Notification category (e.g., SOCIAL, ACADEMIC)', max_length=20, null=True)),
                ('notification_type', models.CharField(blank=True, db_index=True, help_text='Notification type (e.g., LIKE, COMMENT)', max_length=20, null=True)),
                ('context_type', models.CharField(blank=True, db_index=True, help_text='Context type (e.g., Group, Course)', max_length=50, null=True)),
                ('context_id', models.CharField(blank=True, db_index=True, help_text='Context ID', max_length=100, null=True)),
                ('in_app_enabled', models.BooleanField(default=True, help_text='Enable in-app notifications')),
                ('push_enabled', models.BooleanField(default=False, help_text='Enable push notifications')),
                ('email_enabled', models.BooleanField(default=False, help_text='Enable email notifications')),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text='Enable quiet hours')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Quiet hours start time', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Quiet hours end time', null=True)),
                ('muted_until', models.DateTimeField(blank=True, db_index=True, help_text='Temporary mute until this time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'ordering': ['level', 'category', 'notification_type'],
                'indexes': [models.Index(fields=['user'], name='notificatio_user_id_0299fd_idx'), models.Index(fields=['level'], name='notificatio_level_fb74b5_idx'), models.Index(fields=['category'], name='notificatio_categor_930031_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_1fb707_idx'), models.Index(fields=['context_type', 'context_id'], name='notificatio_context_ade746_idx'), models.Index(fields=['muted_until'], name='notificatio_muted_u_3f7cfc_idx'), models.Index(fields=['user', 'level', 'category'], name='notificatio_user_id_85d5ba_idx'), models.Index(fields=['user', 'level', 'notification_type'], name='notificatio_user_id_828e4e_idx')],
                'unique_together': {('user', 'level', 'category', 'notification_type', 'context_type', 'context_id')},
            },
        ),
    ]
