# Generated by Django 5.2.13 on 2026-08-03 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0015_create_notification_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('PUSH', 'Push'), ('EMAIL', 'Email'), ('SMS', 'SMS')], db_index=True, help_text='Delivery channel', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RETRY_SCHEDULED', 'Retry Scheduled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', help_text='Delivery status', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0, help_text='Number of delivery attempts')),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, help_text='Scheduled time for next retry', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed')),
                ('error_code', models.CharField(blank=True, help_text='Error code if delivery failed', max_length=50)),
                ('queued_at', models.DateTimeField(blank=True, help_text='When the delivery was queued', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the delivery was sent', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the delivery was confirmed', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='When the delivery failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(help_text='The notification being delivered', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='notifications.notificationobject')),
            ],
            options={
                'verbose_name': 'Delivery Attempt',
                'verbose_name_plural': 'Delivery Attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification'], name='notificatio_notific_1bd36e_idx'), models.Index(fields=['channel'], name='notificatio_channel_551e36_idx'), models.Index(fields=['status'], name='notificatio_status_d0e2f8_idx'), models.Index(fields=['next_retry_at'], name='notificatio_next_re_dab81f_idx'), models.Index(fields=['created_at'], name='notificatio_created_9d55f1_idx'), models.Index(fields=['notification', 'channel'], name='notificatio_notific_978ae3_idx')],
            },
        ),
    ]
