# Generated by Django 5.2.13 on 2026-08-10 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_update_notification_preference_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
