# Generated by Django 5.2.13 on 2026-08-13 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_delete_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationobject',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Notification Object', 'verbose_name_plural': 'Notification Objects'},
        ),
        migrations.AlterField(
            model_name='notificationobject',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last modification time (only updated during aggregation, not on read status changes)', null=True),
        ),
        migrations.AddIndex(
            model_name='notificationobject',
            index=models.Index(fields=['updated_at'], name='notificatio_updated_218875_idx'),
        ),
    ]
