# Generated by Django 5.2.13 on 2026-09-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0019_alter_notificationobject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationobject',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('MENTION', 'Mention'), ('ASSIGNMENT', 'Assignment'), ('MEETING', 'Meeting'), ('WORKSPACE', 'Workspace'), ('DOCUMENT', 'Document'), ('SECURITY', 'Security'), ('SYSTEM', 'System'), ('AI', 'AI'), ('GROUP', 'Group'), ('FOLLOW', 'Follow'), ('PINCH', 'Pinch'), ('INVITE', 'Invite'), ('SHARE', 'Share'), ('DOCUMENT_SHARED', 'Document Shared')], db_index=True, help_text='Semantic type of the notification', max_length=20),
        ),
    ]
