# Generated by Django 5.2.13 on 2026-09-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0020_alter_notificationobject_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationobject',
            name='notification_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('COMMENT', 'Comment'), ('MENTION', 'Mention'), ('ASSIGNMENT', 'Assignment'), ('MEETING', 'Meeting'), ('WORKSPACE', 'Workspace'), ('DOCUMENT', 'Document'), ('SECURITY', 'Security'), ('SYSTEM', 'System'), ('AI', 'AI'), ('GROUP', 'Group'), ('GROUP_REQUEST', 'Group Join Request'), ('GROUP_APPROVED', 'Group Request Approved'), ('GROUP_REJECTED', 'Group Request Rejected'), ('GROUP_ANNOUNCEMENT', 'Group Announcement'), ('FOLLOW', 'Follow'), ('PINCH', 'Pinch'), ('INVITE', 'Invite'), ('SHARE', 'Share'), ('DOCUMENT_SHARED', 'Document Shared'), ('POST_CREATED', 'Post Created')], db_index=True, help_text='Semantic type of the notification', max_length=20),
        ),
    ]
