# Generated by Django 5.2.13 on 2026-09-08 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0021_alter_notificationobject_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='fcm_token',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='platform',
            field=models.CharField(choices=[('WEB', 'Web Browser'), ('PWA', 'Standalone PWA'), ('ANDROID_NATIVE', 'Android Native'), ('IOS_NATIVE', 'iOS Native')], db_index=True, default='WEB', max_length=20),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='token_type',
            field=models.CharField(choices=[('VAPID', 'VAPID Web Push'), ('FCM', 'Firebase Cloud Messaging'), ('APNS', 'Direct APNs')], default='VAPID', max_length=10),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='auth',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='p256dh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['platform'], name='notificatio_platfor_b2e70c_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['device_id'], name='notificatio_device__641aee_idx'),
        ),
        migrations.AddConstraint(
            model_name='pushsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('endpoint__isnull', False)), fields=('user', 'endpoint'), name='unique_user_web_endpoint'),
        ),
        migrations.AddConstraint(
            model_name='pushsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('fcm_token__isnull', False)), fields=('user', 'fcm_token'), name='unique_user_fcm_token'),
        ),
    ]
