# Generated by Django 5.2.13 on 2026-04-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_attachment_message_attachment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_encrypted',
            field=models.BooleanField(default=True, help_text='End-to-end encryption enabled'),
        ),
        migrations.AddField(
            model_name='conversationmember',
            name='public_key',
            field=models.TextField(blank=True, help_text="User's public key for this conversation", null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='encrypted_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
