# Generated by Django 5.2.13 on 2026-05-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='link_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='link_image',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='link_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='link_type',
            field=models.CharField(blank=True, choices=[('link', 'Link'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('internal_post', 'Internal Post'), ('internal_profile', 'Internal Profile')], default='link', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='link_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
